// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.

package featurebundle

import (
	"errors"

	lipfeature "github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/feature"
)

// contributeFeatureBundleGenerated contributes all non-empty / non-nil planes from FeatureBundle b into cs.
func contributeFeatureBundleGenerated(cs *lipfeature.ContributionSet, pluginID string, b lipfeature.FeatureBundle) error {
	if cs == nil {
		return errors.New("featurebundle: nil ContributionSet")
	}
	if pluginID == "" {
		pluginID = "feature"
	}
	if len(b.SubmitHooks) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneSubmitHooks, pluginID, b.SubmitHooks); err != nil {
			return err
		}
	}
	if len(b.RequestPartHooks) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneRequestPartHooks, pluginID, b.RequestPartHooks); err != nil {
			return err
		}
	}
	if len(b.ResponsePartHooks) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneResponsePartHooks, pluginID, b.ResponsePartHooks); err != nil {
			return err
		}
	}
	if len(b.ToolReactors) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneToolReactors, pluginID, b.ToolReactors); err != nil {
			return err
		}
	}
	if b.SessionOpeners != nil {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneSessionOpeners, pluginID, b.SessionOpeners); err != nil {
			return err
		}
	}
	if b.WorkspaceResolvers != nil {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneWorkspaceResolvers, pluginID, b.WorkspaceResolvers); err != nil {
			return err
		}
	}
	if len(b.ToolCatalogFilters) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneToolCatalogFilters, pluginID, b.ToolCatalogFilters); err != nil {
			return err
		}
	}
	if len(b.ToolCallPolicies) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneToolCallPolicies, pluginID, b.ToolCallPolicies); err != nil {
			return err
		}
	}
	if len(b.ToolCallFinalizers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneToolCallFinalizers, pluginID, b.ToolCallFinalizers); err != nil {
			return err
		}
	}
	if b.ToolCallFinalizationMaxArgsBytes > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneToolCallFinalizationMaxArgsBytes, pluginID, b.ToolCallFinalizationMaxArgsBytes); err != nil {
			return err
		}
	}
	if len(b.RequestTransforms) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneRequestTransforms, pluginID, b.RequestTransforms); err != nil {
			return err
		}
	}
	if len(b.PreRequestHandlers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlanePreRequestHandlers, pluginID, b.PreRequestHandlers); err != nil {
			return err
		}
	}
	if b.RouteHintProviders != nil {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneRouteHintProviders, pluginID, b.RouteHintProviders); err != nil {
			return err
		}
	}
	if b.CompletionGates != nil {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneCompletionGates, pluginID, b.CompletionGates); err != nil {
			return err
		}
	}
	if len(b.AttemptTransforms) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneAttemptTransforms, pluginID, b.AttemptTransforms); err != nil {
			return err
		}
	}
	if len(b.StreamObserverFactories) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneStreamObserverFactories, pluginID, b.StreamObserverFactories); err != nil {
			return err
		}
	}
	if len(b.TrafficObservers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneTrafficObservers, pluginID, b.TrafficObservers); err != nil {
			return err
		}
	}
	if len(b.UsageObservers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneUsageObservers, pluginID, b.UsageObservers); err != nil {
			return err
		}
	}
	if len(b.RawCaptureSinks) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneRawCaptureSinks, pluginID, b.RawCaptureSinks); err != nil {
			return err
		}
	}
	if len(b.TrafficRedactors) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneTrafficRedactors, pluginID, b.TrafficRedactors); err != nil {
			return err
		}
	}
	if len(b.CompactionObservers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneCompactionObservers, pluginID, b.CompactionObservers); err != nil {
			return err
		}
	}
	if len(b.CompactionPreservers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneCompactionPreservers, pluginID, b.CompactionPreservers); err != nil {
			return err
		}
	}
	if len(b.SecretGuards) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneSecretGuards, pluginID, b.SecretGuards); err != nil {
			return err
		}
	}
	if len(b.LocalTurnHandlers) > 0 {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneLocalTurnHandlers, pluginID, b.LocalTurnHandlers); err != nil {
			return err
		}
	}
	if b.TerminalDecisionProvider != nil {
		if err := lipfeature.Contribute(cs, lipfeature.PlaneTerminalDecisionProvider, pluginID, b.TerminalDecisionProvider); err != nil {
			return err
		}
	}
	return nil
}
