// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.

package feature

import (
	"slices"

	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/compaction"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/completion"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/hooks"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/localturn"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/prerequest"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/request"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/response"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/routehint"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/secretguard"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/session"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/terminaldecision"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcall"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcatalog"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolpolicy"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/traffic"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/usage"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/workspace"
)

// generatedContributions holds typed contribution storage for all declared feature planes.
type generatedContributions struct {
	freeze func() *generatedFrozen

	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.
type generatedFrozen struct {
	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// newGeneratedContributions constructs a new generatedContributions with an immutable snapshot freeze function.
func newGeneratedContributions() *generatedContributions {
	gc := &generatedContributions{}
	gc.freeze = func() *generatedFrozen {
		gf := &generatedFrozen{
			submitHooks:                      slices.Clone(gc.submitHooks),
			requestPartHooks:                 slices.Clone(gc.requestPartHooks),
			responsePartHooks:                slices.Clone(gc.responsePartHooks),
			toolReactors:                     slices.Clone(gc.toolReactors),
			sessionOpeners:                   slices.Clone(gc.sessionOpeners),
			workspaceResolvers:               slices.Clone(gc.workspaceResolvers),
			toolCatalogFilters:               slices.Clone(gc.toolCatalogFilters),
			toolCallPolicies:                 slices.Clone(gc.toolCallPolicies),
			toolCallFinalizers:               slices.Clone(gc.toolCallFinalizers),
			toolCallFinalizationMaxArgsBytes: gc.toolCallFinalizationMaxArgsBytes,
			requestTransforms:                slices.Clone(gc.requestTransforms),
			preRequestHandlers:               slices.Clone(gc.preRequestHandlers),
			routeHintProviders:               slices.Clone(gc.routeHintProviders),
			completionGates:                  slices.Clone(gc.completionGates),
			attemptTransforms:                slices.Clone(gc.attemptTransforms),
			streamObserverFactories:          slices.Clone(gc.streamObserverFactories),
			trafficObservers:                 slices.Clone(gc.trafficObservers),
			usageObservers:                   slices.Clone(gc.usageObservers),
			rawCaptureSinks:                  slices.Clone(gc.rawCaptureSinks),
			trafficRedactors:                 slices.Clone(gc.trafficRedactors),
			compactionObservers:              slices.Clone(gc.compactionObservers),
			compactionPreservers:             slices.Clone(gc.compactionPreservers),
			secretGuards:                     slices.Clone(gc.secretGuards),
			localTurnHandlers:                slices.Clone(gc.localTurnHandlers),
			terminalDecisionProvider:         gc.terminalDecisionProvider,
			terminalDecisionProviderID:       gc.terminalDecisionProviderID,
			terminalDecisionProviderHasID:    gc.terminalDecisionProviderHasID,
		}
		return gf
	}
	return gc
}

func init() {
	PlaneSubmitHooks.generated = generatedAccess[[]hooks.SubmitHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.SubmitHook) error {
			combined, err := PlaneSubmitHooks.Combine(SourceFeature, gc.submitHooks, v)
			if err != nil {
				return err
			}
			gc.submitHooks = combined
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.SubmitHook {
			if gf == nil {
				return nil
			}
			return gf.submitHooks
		},
	}
	PlaneRequestPartHooks.generated = generatedAccess[[]hooks.RequestPartHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.RequestPartHook) error {
			combined, err := PlaneRequestPartHooks.Combine(SourceFeature, gc.requestPartHooks, v)
			if err != nil {
				return err
			}
			gc.requestPartHooks = combined
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.RequestPartHook {
			if gf == nil {
				return nil
			}
			return gf.requestPartHooks
		},
	}
	PlaneResponsePartHooks.generated = generatedAccess[[]hooks.ResponsePartHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.ResponsePartHook) error {
			combined, err := PlaneResponsePartHooks.Combine(SourceFeature, gc.responsePartHooks, v)
			if err != nil {
				return err
			}
			gc.responsePartHooks = combined
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ResponsePartHook {
			if gf == nil {
				return nil
			}
			return gf.responsePartHooks
		},
	}
	PlaneToolReactors.generated = generatedAccess[[]hooks.ToolReactor]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.ToolReactor) error {
			combined, err := PlaneToolReactors.Combine(SourceFeature, gc.toolReactors, v)
			if err != nil {
				return err
			}
			gc.toolReactors = combined
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ToolReactor {
			if gf == nil {
				return nil
			}
			return gf.toolReactors
		},
	}
	PlaneSessionOpeners.generated = generatedAccess[[]session.Opener]{
		contribute: func(gc *generatedContributions, pluginID string, v []session.Opener) error {
			combined, err := PlaneSessionOpeners.Combine(SourceFeature, gc.sessionOpeners, v)
			if err != nil {
				return err
			}
			gc.sessionOpeners = combined
			return nil
		},
		get: func(gf *generatedFrozen) []session.Opener {
			if gf == nil {
				return nil
			}
			return gf.sessionOpeners
		},
	}
	PlaneWorkspaceResolvers.generated = generatedAccess[[]workspace.Resolver]{
		contribute: func(gc *generatedContributions, pluginID string, v []workspace.Resolver) error {
			combined, err := PlaneWorkspaceResolvers.Combine(SourceFeature, gc.workspaceResolvers, v)
			if err != nil {
				return err
			}
			gc.workspaceResolvers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []workspace.Resolver {
			if gf == nil {
				return nil
			}
			return gf.workspaceResolvers
		},
	}
	PlaneToolCatalogFilters.generated = generatedAccess[[]toolcatalog.Filter]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolcatalog.Filter) error {
			combined, err := PlaneToolCatalogFilters.Combine(SourceFeature, gc.toolCatalogFilters, v)
			if err != nil {
				return err
			}
			gc.toolCatalogFilters = combined
			return nil
		},
		get: func(gf *generatedFrozen) []toolcatalog.Filter {
			if gf == nil {
				return nil
			}
			return gf.toolCatalogFilters
		},
	}
	PlaneToolCallPolicies.generated = generatedAccess[[]toolpolicy.Policy]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolpolicy.Policy) error {
			combined, err := PlaneToolCallPolicies.Combine(SourceFeature, gc.toolCallPolicies, v)
			if err != nil {
				return err
			}
			gc.toolCallPolicies = combined
			return nil
		},
		get: func(gf *generatedFrozen) []toolpolicy.Policy {
			if gf == nil {
				return nil
			}
			return gf.toolCallPolicies
		},
	}
	PlaneToolCallFinalizers.generated = generatedAccess[[]toolcall.Finalizer]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolcall.Finalizer) error {
			combined, err := PlaneToolCallFinalizers.Combine(SourceFeature, gc.toolCallFinalizers, v)
			if err != nil {
				return err
			}
			gc.toolCallFinalizers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []toolcall.Finalizer {
			if gf == nil {
				return nil
			}
			return gf.toolCallFinalizers
		},
	}
	PlaneToolCallFinalizationMaxArgsBytes.generated = generatedAccess[int]{
		contribute: func(gc *generatedContributions, pluginID string, v int) error {
			combined, err := PlaneToolCallFinalizationMaxArgsBytes.Combine(SourceFeature, gc.toolCallFinalizationMaxArgsBytes, v)
			if err != nil {
				return err
			}
			gc.toolCallFinalizationMaxArgsBytes = combined
			return nil
		},
		get: func(gf *generatedFrozen) int {
			if gf == nil {
				return 0
			}
			return gf.toolCallFinalizationMaxArgsBytes
		},
	}
	PlaneRequestTransforms.generated = generatedAccess[[]request.Transform]{
		contribute: func(gc *generatedContributions, pluginID string, v []request.Transform) error {
			combined, err := PlaneRequestTransforms.Combine(SourceFeature, gc.requestTransforms, v)
			if err != nil {
				return err
			}
			gc.requestTransforms = combined
			return nil
		},
		get: func(gf *generatedFrozen) []request.Transform {
			if gf == nil {
				return nil
			}
			return gf.requestTransforms
		},
	}
	PlanePreRequestHandlers.generated = generatedAccess[[]prerequest.Handler]{
		contribute: func(gc *generatedContributions, pluginID string, v []prerequest.Handler) error {
			combined, err := PlanePreRequestHandlers.Combine(SourceFeature, gc.preRequestHandlers, v)
			if err != nil {
				return err
			}
			gc.preRequestHandlers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []prerequest.Handler {
			if gf == nil {
				return nil
			}
			return gf.preRequestHandlers
		},
	}
	PlaneRouteHintProviders.generated = generatedAccess[[]routehint.Provider]{
		contribute: func(gc *generatedContributions, pluginID string, v []routehint.Provider) error {
			combined, err := PlaneRouteHintProviders.Combine(SourceFeature, gc.routeHintProviders, v)
			if err != nil {
				return err
			}
			gc.routeHintProviders = combined
			return nil
		},
		get: func(gf *generatedFrozen) []routehint.Provider {
			if gf == nil {
				return nil
			}
			return gf.routeHintProviders
		},
	}
	PlaneCompletionGates.generated = generatedAccess[[]completion.Gate]{
		contribute: func(gc *generatedContributions, pluginID string, v []completion.Gate) error {
			combined, err := PlaneCompletionGates.Combine(SourceFeature, gc.completionGates, v)
			if err != nil {
				return err
			}
			gc.completionGates = combined
			return nil
		},
		get: func(gf *generatedFrozen) []completion.Gate {
			if gf == nil {
				return nil
			}
			return gf.completionGates
		},
	}
	PlaneAttemptTransforms.generated = generatedAccess[[]request.AttemptTransform]{
		contribute: func(gc *generatedContributions, pluginID string, v []request.AttemptTransform) error {
			combined, err := PlaneAttemptTransforms.Combine(SourceFeature, gc.attemptTransforms, v)
			if err != nil {
				return err
			}
			gc.attemptTransforms = combined
			return nil
		},
		get: func(gf *generatedFrozen) []request.AttemptTransform {
			if gf == nil {
				return nil
			}
			return gf.attemptTransforms
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneAttemptTransforms.Identity(gf.attemptTransforms)
		},
	}
	PlaneStreamObserverFactories.generated = generatedAccess[[]response.StreamObserverFactory]{
		contribute: func(gc *generatedContributions, pluginID string, v []response.StreamObserverFactory) error {
			combined, err := PlaneStreamObserverFactories.Combine(SourceFeature, gc.streamObserverFactories, v)
			if err != nil {
				return err
			}
			gc.streamObserverFactories = combined
			return nil
		},
		get: func(gf *generatedFrozen) []response.StreamObserverFactory {
			if gf == nil {
				return nil
			}
			return gf.streamObserverFactories
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneStreamObserverFactories.Identity(gf.streamObserverFactories)
		},
	}
	PlaneTrafficObservers.generated = generatedAccess[[]traffic.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.Observer) error {
			combined, err := PlaneTrafficObservers.Combine(SourceFeature, gc.trafficObservers, v)
			if err != nil {
				return err
			}
			gc.trafficObservers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Observer {
			if gf == nil {
				return nil
			}
			return gf.trafficObservers
		},
	}
	PlaneUsageObservers.generated = generatedAccess[[]usage.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []usage.Observer) error {
			combined, err := PlaneUsageObservers.Combine(SourceFeature, gc.usageObservers, v)
			if err != nil {
				return err
			}
			gc.usageObservers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []usage.Observer {
			if gf == nil {
				return nil
			}
			return gf.usageObservers
		},
	}
	PlaneRawCaptureSinks.generated = generatedAccess[[]traffic.RawCaptureSink]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.RawCaptureSink) error {
			combined, err := PlaneRawCaptureSinks.Combine(SourceFeature, gc.rawCaptureSinks, v)
			if err != nil {
				return err
			}
			gc.rawCaptureSinks = combined
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.RawCaptureSink {
			if gf == nil {
				return nil
			}
			return gf.rawCaptureSinks
		},
	}
	PlaneTrafficRedactors.generated = generatedAccess[[]traffic.Redactor]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.Redactor) error {
			combined, err := PlaneTrafficRedactors.Combine(SourceFeature, gc.trafficRedactors, v)
			if err != nil {
				return err
			}
			gc.trafficRedactors = combined
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Redactor {
			if gf == nil {
				return nil
			}
			return gf.trafficRedactors
		},
	}
	PlaneCompactionObservers.generated = generatedAccess[[]compaction.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []compaction.Observer) error {
			combined, err := PlaneCompactionObservers.Combine(SourceFeature, gc.compactionObservers, v)
			if err != nil {
				return err
			}
			gc.compactionObservers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Observer {
			if gf == nil {
				return nil
			}
			return gf.compactionObservers
		},
	}
	PlaneCompactionPreservers.generated = generatedAccess[[]compaction.Preserver]{
		contribute: func(gc *generatedContributions, pluginID string, v []compaction.Preserver) error {
			combined, err := PlaneCompactionPreservers.Combine(SourceFeature, gc.compactionPreservers, v)
			if err != nil {
				return err
			}
			gc.compactionPreservers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Preserver {
			if gf == nil {
				return nil
			}
			return gf.compactionPreservers
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneCompactionPreservers.Identity(gf.compactionPreservers)
		},
	}
	PlaneSecretGuards.generated = generatedAccess[[]secretguard.Guard]{
		contribute: func(gc *generatedContributions, pluginID string, v []secretguard.Guard) error {
			combined, err := PlaneSecretGuards.Combine(SourceFeature, gc.secretGuards, v)
			if err != nil {
				return err
			}
			gc.secretGuards = combined
			return nil
		},
		get: func(gf *generatedFrozen) []secretguard.Guard {
			if gf == nil {
				return nil
			}
			return gf.secretGuards
		},
	}
	PlaneLocalTurnHandlers.generated = generatedAccess[[]localturn.Handler]{
		contribute: func(gc *generatedContributions, pluginID string, v []localturn.Handler) error {
			combined, err := PlaneLocalTurnHandlers.Combine(SourceFeature, gc.localTurnHandlers, v)
			if err != nil {
				return err
			}
			gc.localTurnHandlers = combined
			return nil
		},
		get: func(gf *generatedFrozen) []localturn.Handler {
			if gf == nil {
				return nil
			}
			return gf.localTurnHandlers
		},
	}
	PlaneTerminalDecisionProvider.generated = generatedAccess[terminaldecision.Provider]{
		contribute: func(gc *generatedContributions, pluginID string, v terminaldecision.Provider) error {
			combined, err := PlaneTerminalDecisionProvider.Combine(SourceFeature, gc.terminalDecisionProvider, v)
			if err != nil {
				return err
			}
			gc.terminalDecisionProvider = combined
			id, hasID := PlaneTerminalDecisionProvider.Identity(v)
			gc.terminalDecisionProviderID = id
			gc.terminalDecisionProviderHasID = hasID
			return nil
		},
		get: func(gf *generatedFrozen) terminaldecision.Provider {
			if gf == nil {
				return nil
			}
			return gf.terminalDecisionProvider
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return gf.terminalDecisionProviderID, gf.terminalDecisionProviderHasID
		},
	}
}
