// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.

package feature

import (
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/compaction"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/completion"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/hooks"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/localturn"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/prerequest"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/request"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/response"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/routehint"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/secretguard"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/session"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/terminaldecision"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcall"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcatalog"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolpolicy"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/traffic"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/usage"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/workspace"
)

// generatedContributions holds typed contribution storage for all declared feature planes.
type generatedContributions struct {
	freeze func() *generatedFrozen

	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.
type generatedFrozen struct {
	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// newGeneratedContributions constructs a new generatedContributions with an immutable snapshot freeze function.
func newGeneratedContributions() *generatedContributions {
	gc := &generatedContributions{}
	gc.freeze = func() *generatedFrozen {
		gf := &generatedFrozen{
			submitHooks:                      cloneSlice(gc.submitHooks),
			requestPartHooks:                 cloneSlice(gc.requestPartHooks),
			responsePartHooks:                cloneSlice(gc.responsePartHooks),
			toolReactors:                     cloneSlice(gc.toolReactors),
			sessionOpeners:                   cloneSlice(gc.sessionOpeners),
			workspaceResolvers:               cloneSlice(gc.workspaceResolvers),
			toolCatalogFilters:               cloneSlice(gc.toolCatalogFilters),
			toolCallPolicies:                 cloneSlice(gc.toolCallPolicies),
			toolCallFinalizers:               cloneSlice(gc.toolCallFinalizers),
			toolCallFinalizationMaxArgsBytes: gc.toolCallFinalizationMaxArgsBytes,
			requestTransforms:                cloneSlice(gc.requestTransforms),
			preRequestHandlers:               cloneSlice(gc.preRequestHandlers),
			routeHintProviders:               cloneSlice(gc.routeHintProviders),
			completionGates:                  cloneSlice(gc.completionGates),
			attemptTransforms:                cloneSlice(gc.attemptTransforms),
			streamObserverFactories:          cloneSlice(gc.streamObserverFactories),
			trafficObservers:                 cloneSlice(gc.trafficObservers),
			usageObservers:                   cloneSlice(gc.usageObservers),
			rawCaptureSinks:                  cloneSlice(gc.rawCaptureSinks),
			trafficRedactors:                 cloneSlice(gc.trafficRedactors),
			compactionObservers:              cloneSlice(gc.compactionObservers),
			compactionPreservers:             cloneSlice(gc.compactionPreservers),
			secretGuards:                     cloneSlice(gc.secretGuards),
			localTurnHandlers:                cloneSlice(gc.localTurnHandlers),
			terminalDecisionProvider:         gc.terminalDecisionProvider,
			terminalDecisionProviderID:       gc.terminalDecisionProviderID,
			terminalDecisionProviderHasID:    gc.terminalDecisionProviderHasID,
		}
		return gf
	}
	return gc
}

func init() {
	PlaneSubmitHooks.generated = generatedAccess[[]hooks.SubmitHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.SubmitHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.submitHooks)
			combined, err := PlaneSubmitHooks.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.submitHooks != nil) && combined == nil {
				combined = make([]hooks.SubmitHook, 0)
			}
			gc.submitHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.SubmitHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.submitHooks)
		},
	}
	PlaneRequestPartHooks.generated = generatedAccess[[]hooks.RequestPartHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.RequestPartHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.requestPartHooks)
			combined, err := PlaneRequestPartHooks.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.requestPartHooks != nil) && combined == nil {
				combined = make([]hooks.RequestPartHook, 0)
			}
			gc.requestPartHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.RequestPartHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.requestPartHooks)
		},
	}
	PlaneResponsePartHooks.generated = generatedAccess[[]hooks.ResponsePartHook]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.ResponsePartHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.responsePartHooks)
			combined, err := PlaneResponsePartHooks.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.responsePartHooks != nil) && combined == nil {
				combined = make([]hooks.ResponsePartHook, 0)
			}
			gc.responsePartHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ResponsePartHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.responsePartHooks)
		},
	}
	PlaneToolReactors.generated = generatedAccess[[]hooks.ToolReactor]{
		contribute: func(gc *generatedContributions, pluginID string, v []hooks.ToolReactor) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolReactors)
			combined, err := PlaneToolReactors.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolReactors != nil) && combined == nil {
				combined = make([]hooks.ToolReactor, 0)
			}
			gc.toolReactors = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ToolReactor {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolReactors)
		},
	}
	PlaneSessionOpeners.generated = generatedAccess[[]session.Opener]{
		contribute: func(gc *generatedContributions, pluginID string, v []session.Opener) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.sessionOpeners)
			combined, err := PlaneSessionOpeners.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.sessionOpeners != nil) && combined == nil {
				combined = make([]session.Opener, 0)
			}
			gc.sessionOpeners = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []session.Opener {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.sessionOpeners)
		},
	}
	PlaneWorkspaceResolvers.generated = generatedAccess[[]workspace.Resolver]{
		contribute: func(gc *generatedContributions, pluginID string, v []workspace.Resolver) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.workspaceResolvers)
			combined, err := PlaneWorkspaceResolvers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.workspaceResolvers != nil) && combined == nil {
				combined = make([]workspace.Resolver, 0)
			}
			gc.workspaceResolvers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []workspace.Resolver {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.workspaceResolvers)
		},
	}
	PlaneToolCatalogFilters.generated = generatedAccess[[]toolcatalog.Filter]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolcatalog.Filter) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCatalogFilters)
			combined, err := PlaneToolCatalogFilters.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCatalogFilters != nil) && combined == nil {
				combined = make([]toolcatalog.Filter, 0)
			}
			gc.toolCatalogFilters = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolcatalog.Filter {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCatalogFilters)
		},
	}
	PlaneToolCallPolicies.generated = generatedAccess[[]toolpolicy.Policy]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolpolicy.Policy) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCallPolicies)
			combined, err := PlaneToolCallPolicies.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCallPolicies != nil) && combined == nil {
				combined = make([]toolpolicy.Policy, 0)
			}
			gc.toolCallPolicies = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolpolicy.Policy {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCallPolicies)
		},
	}
	PlaneToolCallFinalizers.generated = generatedAccess[[]toolcall.Finalizer]{
		contribute: func(gc *generatedContributions, pluginID string, v []toolcall.Finalizer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCallFinalizers)
			combined, err := PlaneToolCallFinalizers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCallFinalizers != nil) && combined == nil {
				combined = make([]toolcall.Finalizer, 0)
			}
			gc.toolCallFinalizers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolcall.Finalizer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCallFinalizers)
		},
	}
	PlaneToolCallFinalizationMaxArgsBytes.generated = generatedAccess[int]{
		contribute: func(gc *generatedContributions, pluginID string, v int) error {
			combined, err := PlaneToolCallFinalizationMaxArgsBytes.Combine(SourceFeature, gc.toolCallFinalizationMaxArgsBytes, v)
			if err != nil {
				return err
			}
			gc.toolCallFinalizationMaxArgsBytes = combined
			return nil
		},
		get: func(gf *generatedFrozen) int {
			if gf == nil {
				return 0
			}
			return gf.toolCallFinalizationMaxArgsBytes
		},
	}
	PlaneRequestTransforms.generated = generatedAccess[[]request.Transform]{
		contribute: func(gc *generatedContributions, pluginID string, v []request.Transform) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.requestTransforms)
			combined, err := PlaneRequestTransforms.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.requestTransforms != nil) && combined == nil {
				combined = make([]request.Transform, 0)
			}
			gc.requestTransforms = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []request.Transform {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.requestTransforms)
		},
	}
	PlanePreRequestHandlers.generated = generatedAccess[[]prerequest.Handler]{
		contribute: func(gc *generatedContributions, pluginID string, v []prerequest.Handler) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.preRequestHandlers)
			combined, err := PlanePreRequestHandlers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.preRequestHandlers != nil) && combined == nil {
				combined = make([]prerequest.Handler, 0)
			}
			gc.preRequestHandlers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []prerequest.Handler {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.preRequestHandlers)
		},
	}
	PlaneRouteHintProviders.generated = generatedAccess[[]routehint.Provider]{
		contribute: func(gc *generatedContributions, pluginID string, v []routehint.Provider) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.routeHintProviders)
			combined, err := PlaneRouteHintProviders.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.routeHintProviders != nil) && combined == nil {
				combined = make([]routehint.Provider, 0)
			}
			gc.routeHintProviders = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []routehint.Provider {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.routeHintProviders)
		},
	}
	PlaneCompletionGates.generated = generatedAccess[[]completion.Gate]{
		contribute: func(gc *generatedContributions, pluginID string, v []completion.Gate) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.completionGates)
			combined, err := PlaneCompletionGates.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.completionGates != nil) && combined == nil {
				combined = make([]completion.Gate, 0)
			}
			gc.completionGates = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []completion.Gate {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.completionGates)
		},
	}
	PlaneAttemptTransforms.generated = generatedAccess[[]request.AttemptTransform]{
		contribute: func(gc *generatedContributions, pluginID string, v []request.AttemptTransform) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.attemptTransforms)
			combined, err := PlaneAttemptTransforms.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.attemptTransforms != nil) && combined == nil {
				combined = make([]request.AttemptTransform, 0)
			}
			gc.attemptTransforms = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []request.AttemptTransform {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.attemptTransforms)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneAttemptTransforms.Identity(gf.attemptTransforms)
		},
	}
	PlaneStreamObserverFactories.generated = generatedAccess[[]response.StreamObserverFactory]{
		contribute: func(gc *generatedContributions, pluginID string, v []response.StreamObserverFactory) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.streamObserverFactories)
			combined, err := PlaneStreamObserverFactories.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.streamObserverFactories != nil) && combined == nil {
				combined = make([]response.StreamObserverFactory, 0)
			}
			gc.streamObserverFactories = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []response.StreamObserverFactory {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.streamObserverFactories)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneStreamObserverFactories.Identity(gf.streamObserverFactories)
		},
	}
	PlaneTrafficObservers.generated = generatedAccess[[]traffic.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.trafficObservers)
			combined, err := PlaneTrafficObservers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.trafficObservers != nil) && combined == nil {
				combined = make([]traffic.Observer, 0)
			}
			gc.trafficObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.trafficObservers)
		},
	}
	PlaneUsageObservers.generated = generatedAccess[[]usage.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []usage.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.usageObservers)
			combined, err := PlaneUsageObservers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.usageObservers != nil) && combined == nil {
				combined = make([]usage.Observer, 0)
			}
			gc.usageObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []usage.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.usageObservers)
		},
	}
	PlaneRawCaptureSinks.generated = generatedAccess[[]traffic.RawCaptureSink]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.RawCaptureSink) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.rawCaptureSinks)
			combined, err := PlaneRawCaptureSinks.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.rawCaptureSinks != nil) && combined == nil {
				combined = make([]traffic.RawCaptureSink, 0)
			}
			gc.rawCaptureSinks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.RawCaptureSink {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.rawCaptureSinks)
		},
	}
	PlaneTrafficRedactors.generated = generatedAccess[[]traffic.Redactor]{
		contribute: func(gc *generatedContributions, pluginID string, v []traffic.Redactor) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.trafficRedactors)
			combined, err := PlaneTrafficRedactors.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.trafficRedactors != nil) && combined == nil {
				combined = make([]traffic.Redactor, 0)
			}
			gc.trafficRedactors = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Redactor {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.trafficRedactors)
		},
	}
	PlaneCompactionObservers.generated = generatedAccess[[]compaction.Observer]{
		contribute: func(gc *generatedContributions, pluginID string, v []compaction.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.compactionObservers)
			combined, err := PlaneCompactionObservers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.compactionObservers != nil) && combined == nil {
				combined = make([]compaction.Observer, 0)
			}
			gc.compactionObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.compactionObservers)
		},
	}
	PlaneCompactionPreservers.generated = generatedAccess[[]compaction.Preserver]{
		contribute: func(gc *generatedContributions, pluginID string, v []compaction.Preserver) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.compactionPreservers)
			combined, err := PlaneCompactionPreservers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.compactionPreservers != nil) && combined == nil {
				combined = make([]compaction.Preserver, 0)
			}
			gc.compactionPreservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Preserver {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.compactionPreservers)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneCompactionPreservers.Identity(gf.compactionPreservers)
		},
	}
	PlaneSecretGuards.generated = generatedAccess[[]secretguard.Guard]{
		contribute: func(gc *generatedContributions, pluginID string, v []secretguard.Guard) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.secretGuards)
			combined, err := PlaneSecretGuards.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.secretGuards != nil) && combined == nil {
				combined = make([]secretguard.Guard, 0)
			}
			gc.secretGuards = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []secretguard.Guard {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.secretGuards)
		},
	}
	PlaneLocalTurnHandlers.generated = generatedAccess[[]localturn.Handler]{
		contribute: func(gc *generatedContributions, pluginID string, v []localturn.Handler) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.localTurnHandlers)
			combined, err := PlaneLocalTurnHandlers.Combine(SourceFeature, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.localTurnHandlers != nil) && combined == nil {
				combined = make([]localturn.Handler, 0)
			}
			gc.localTurnHandlers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []localturn.Handler {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.localTurnHandlers)
		},
	}
	PlaneTerminalDecisionProvider.generated = generatedAccess[terminaldecision.Provider]{
		contribute: func(gc *generatedContributions, pluginID string, v terminaldecision.Provider) error {
			combined, err := PlaneTerminalDecisionProvider.Combine(SourceFeature, gc.terminalDecisionProvider, v)
			if err != nil {
				return err
			}
			gc.terminalDecisionProvider = combined
			id, hasID := PlaneTerminalDecisionProvider.Identity(v)
			gc.terminalDecisionProviderID = id
			gc.terminalDecisionProviderHasID = hasID
			return nil
		},
		get: func(gf *generatedFrozen) terminaldecision.Provider {
			if gf == nil {
				return nil
			}
			return gf.terminalDecisionProvider
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return gf.terminalDecisionProviderID, gf.terminalDecisionProviderHasID
		},
	}
}
