// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.

package feature

import (
	"fmt"

	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/compaction"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/completion"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/hooks"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/localturn"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/prerequest"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/request"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/response"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/routehint"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/secretguard"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/session"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/terminaldecision"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcall"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolcatalog"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/toolpolicy"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/traffic"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/usage"
	"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/workspace"
)

// generatedContributions holds typed contribution storage for all declared feature planes.
type generatedContributions struct {
	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.
type generatedFrozen struct {
	submitHooks                      []hooks.SubmitHook
	requestPartHooks                 []hooks.RequestPartHook
	responsePartHooks                []hooks.ResponsePartHook
	toolReactors                     []hooks.ToolReactor
	sessionOpeners                   []session.Opener
	workspaceResolvers               []workspace.Resolver
	toolCatalogFilters               []toolcatalog.Filter
	toolCallPolicies                 []toolpolicy.Policy
	toolCallFinalizers               []toolcall.Finalizer
	toolCallFinalizationMaxArgsBytes int
	requestTransforms                []request.Transform
	preRequestHandlers               []prerequest.Handler
	routeHintProviders               []routehint.Provider
	completionGates                  []completion.Gate
	attemptTransforms                []request.AttemptTransform
	streamObserverFactories          []response.StreamObserverFactory
	trafficObservers                 []traffic.Observer
	usageObservers                   []usage.Observer
	rawCaptureSinks                  []traffic.RawCaptureSink
	trafficRedactors                 []traffic.Redactor
	compactionObservers              []compaction.Observer
	compactionPreservers             []compaction.Preserver
	secretGuards                     []secretguard.Guard
	localTurnHandlers                []localturn.Handler
	terminalDecisionProvider         terminaldecision.Provider
	terminalDecisionProviderID       string
	terminalDecisionProviderHasID    bool
}

// newGeneratedContributions constructs a new empty generatedContributions.
func newGeneratedContributions() *generatedContributions {
	return &generatedContributions{}
}

func (gc *generatedContributions) clone() *generatedContributions {
	if gc == nil {
		return nil
	}
	next := newGeneratedContributions()
	next.submitHooks = cloneSlice(gc.submitHooks)
	next.requestPartHooks = cloneSlice(gc.requestPartHooks)
	next.responsePartHooks = cloneSlice(gc.responsePartHooks)
	next.toolReactors = cloneSlice(gc.toolReactors)
	next.sessionOpeners = cloneSlice(gc.sessionOpeners)
	next.workspaceResolvers = cloneSlice(gc.workspaceResolvers)
	next.toolCatalogFilters = cloneSlice(gc.toolCatalogFilters)
	next.toolCallPolicies = cloneSlice(gc.toolCallPolicies)
	next.toolCallFinalizers = cloneSlice(gc.toolCallFinalizers)
	next.toolCallFinalizationMaxArgsBytes = gc.toolCallFinalizationMaxArgsBytes
	next.requestTransforms = cloneSlice(gc.requestTransforms)
	next.preRequestHandlers = cloneSlice(gc.preRequestHandlers)
	next.routeHintProviders = cloneSlice(gc.routeHintProviders)
	next.completionGates = cloneSlice(gc.completionGates)
	next.attemptTransforms = cloneSlice(gc.attemptTransforms)
	next.streamObserverFactories = cloneSlice(gc.streamObserverFactories)
	next.trafficObservers = cloneSlice(gc.trafficObservers)
	next.usageObservers = cloneSlice(gc.usageObservers)
	next.rawCaptureSinks = cloneSlice(gc.rawCaptureSinks)
	next.trafficRedactors = cloneSlice(gc.trafficRedactors)
	next.compactionObservers = cloneSlice(gc.compactionObservers)
	next.compactionPreservers = cloneSlice(gc.compactionPreservers)
	next.secretGuards = cloneSlice(gc.secretGuards)
	next.localTurnHandlers = cloneSlice(gc.localTurnHandlers)
	next.terminalDecisionProvider = gc.terminalDecisionProvider
	next.terminalDecisionProviderID = gc.terminalDecisionProviderID
	next.terminalDecisionProviderHasID = gc.terminalDecisionProviderHasID
	return next
}

func (gc *generatedContributions) freeze() *generatedFrozen {
	if gc == nil {
		return nil
	}
	gf := &generatedFrozen{
		submitHooks:                      cloneSlice(gc.submitHooks),
		requestPartHooks:                 cloneSlice(gc.requestPartHooks),
		responsePartHooks:                cloneSlice(gc.responsePartHooks),
		toolReactors:                     cloneSlice(gc.toolReactors),
		sessionOpeners:                   cloneSlice(gc.sessionOpeners),
		workspaceResolvers:               cloneSlice(gc.workspaceResolvers),
		toolCatalogFilters:               cloneSlice(gc.toolCatalogFilters),
		toolCallPolicies:                 cloneSlice(gc.toolCallPolicies),
		toolCallFinalizers:               cloneSlice(gc.toolCallFinalizers),
		toolCallFinalizationMaxArgsBytes: gc.toolCallFinalizationMaxArgsBytes,
		requestTransforms:                cloneSlice(gc.requestTransforms),
		preRequestHandlers:               cloneSlice(gc.preRequestHandlers),
		routeHintProviders:               cloneSlice(gc.routeHintProviders),
		completionGates:                  cloneSlice(gc.completionGates),
		attemptTransforms:                cloneSlice(gc.attemptTransforms),
		streamObserverFactories:          cloneSlice(gc.streamObserverFactories),
		trafficObservers:                 cloneSlice(gc.trafficObservers),
		usageObservers:                   cloneSlice(gc.usageObservers),
		rawCaptureSinks:                  cloneSlice(gc.rawCaptureSinks),
		trafficRedactors:                 cloneSlice(gc.trafficRedactors),
		compactionObservers:              cloneSlice(gc.compactionObservers),
		compactionPreservers:             cloneSlice(gc.compactionPreservers),
		secretGuards:                     cloneSlice(gc.secretGuards),
		localTurnHandlers:                cloneSlice(gc.localTurnHandlers),
		terminalDecisionProvider:         gc.terminalDecisionProvider,
		terminalDecisionProviderID:       gc.terminalDecisionProviderID,
		terminalDecisionProviderHasID:    gc.terminalDecisionProviderHasID,
	}
	return gf
}

func (gf *generatedFrozen) toContributions() *generatedContributions {
	if gf == nil {
		return newGeneratedContributions()
	}
	gc := newGeneratedContributions()
	gc.submitHooks = cloneSlice(gf.submitHooks)
	gc.requestPartHooks = cloneSlice(gf.requestPartHooks)
	gc.responsePartHooks = cloneSlice(gf.responsePartHooks)
	gc.toolReactors = cloneSlice(gf.toolReactors)
	gc.sessionOpeners = cloneSlice(gf.sessionOpeners)
	gc.workspaceResolvers = cloneSlice(gf.workspaceResolvers)
	gc.toolCatalogFilters = cloneSlice(gf.toolCatalogFilters)
	gc.toolCallPolicies = cloneSlice(gf.toolCallPolicies)
	gc.toolCallFinalizers = cloneSlice(gf.toolCallFinalizers)
	gc.toolCallFinalizationMaxArgsBytes = gf.toolCallFinalizationMaxArgsBytes
	gc.requestTransforms = cloneSlice(gf.requestTransforms)
	gc.preRequestHandlers = cloneSlice(gf.preRequestHandlers)
	gc.routeHintProviders = cloneSlice(gf.routeHintProviders)
	gc.completionGates = cloneSlice(gf.completionGates)
	gc.attemptTransforms = cloneSlice(gf.attemptTransforms)
	gc.streamObserverFactories = cloneSlice(gf.streamObserverFactories)
	gc.trafficObservers = cloneSlice(gf.trafficObservers)
	gc.usageObservers = cloneSlice(gf.usageObservers)
	gc.rawCaptureSinks = cloneSlice(gf.rawCaptureSinks)
	gc.trafficRedactors = cloneSlice(gf.trafficRedactors)
	gc.compactionObservers = cloneSlice(gf.compactionObservers)
	gc.compactionPreservers = cloneSlice(gf.compactionPreservers)
	gc.secretGuards = cloneSlice(gf.secretGuards)
	gc.localTurnHandlers = cloneSlice(gf.localTurnHandlers)
	gc.terminalDecisionProvider = gf.terminalDecisionProvider
	gc.terminalDecisionProviderID = gf.terminalDecisionProviderID
	gc.terminalDecisionProviderHasID = gf.terminalDecisionProviderHasID
	return gc
}

func (gf *generatedFrozen) freezeRequest() *generatedFrozen {
	if gf == nil {
		return nil
	}
	next := &generatedFrozen{
		submitHooks:                      cloneSlice(gf.submitHooks),
		requestPartHooks:                 cloneSlice(gf.requestPartHooks),
		responsePartHooks:                cloneSlice(gf.responsePartHooks),
		toolReactors:                     cloneSlice(gf.toolReactors),
		sessionOpeners:                   materializeRequestSlice(gf.sessionOpeners, PlaneSessionOpeners.RequestMaterializer),
		workspaceResolvers:               cloneSlice(gf.workspaceResolvers),
		toolCatalogFilters:               cloneSlice(gf.toolCatalogFilters),
		toolCallPolicies:                 materializeRequestSlice(gf.toolCallPolicies, PlaneToolCallPolicies.RequestMaterializer),
		toolCallFinalizers:               materializeRequestSlice(gf.toolCallFinalizers, PlaneToolCallFinalizers.RequestMaterializer),
		toolCallFinalizationMaxArgsBytes: gf.toolCallFinalizationMaxArgsBytes,
		requestTransforms:                cloneSlice(gf.requestTransforms),
		preRequestHandlers:               materializeRequestSlice(gf.preRequestHandlers, PlanePreRequestHandlers.RequestMaterializer),
		routeHintProviders:               cloneSlice(gf.routeHintProviders),
		completionGates:                  cloneSlice(gf.completionGates),
		attemptTransforms:                materializeRequestSlice(gf.attemptTransforms, PlaneAttemptTransforms.RequestMaterializer),
		streamObserverFactories:          materializeRequestSlice(gf.streamObserverFactories, PlaneStreamObserverFactories.RequestMaterializer),
		trafficObservers:                 cloneSlice(gf.trafficObservers),
		usageObservers:                   cloneSlice(gf.usageObservers),
		rawCaptureSinks:                  cloneSlice(gf.rawCaptureSinks),
		trafficRedactors:                 materializeRequestSlice(gf.trafficRedactors, PlaneTrafficRedactors.RequestMaterializer),
		compactionObservers:              cloneSlice(gf.compactionObservers),
		compactionPreservers:             cloneSlice(gf.compactionPreservers),
		secretGuards:                     materializeRequestSlice(gf.secretGuards, PlaneSecretGuards.RequestMaterializer),
		localTurnHandlers:                materializeRequestSlice(gf.localTurnHandlers, PlaneLocalTurnHandlers.RequestMaterializer),
		terminalDecisionProvider:         gf.terminalDecisionProvider,
		terminalDecisionProviderID:       gf.terminalDecisionProviderID,
		terminalDecisionProviderHasID:    gf.terminalDecisionProviderHasID,
	}
	return next
}

func (gf *generatedFrozen) contributeCandidateTo(gc *generatedContributions, source SourceKind, contributorID string) error {
	if gf == nil || gc == nil {
		return nil
	}
	if gf.sessionOpeners != nil {
		if PlaneSessionOpeners.Validate != nil {
			if err := PlaneSessionOpeners.Validate(gf.sessionOpeners); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneSessionOpeners.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneSessionOpeners.generated.contribute(gc, source, contributorID, gf.sessionOpeners); err != nil {
			return err
		}
	}
	if gf.workspaceResolvers != nil {
		if PlaneWorkspaceResolvers.Validate != nil {
			if err := PlaneWorkspaceResolvers.Validate(gf.workspaceResolvers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneWorkspaceResolvers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneWorkspaceResolvers.generated.contribute(gc, source, contributorID, gf.workspaceResolvers); err != nil {
			return err
		}
	}
	if gf.toolCatalogFilters != nil {
		if PlaneToolCatalogFilters.Validate != nil {
			if err := PlaneToolCatalogFilters.Validate(gf.toolCatalogFilters); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCatalogFilters.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneToolCatalogFilters.generated.contribute(gc, source, contributorID, gf.toolCatalogFilters); err != nil {
			return err
		}
	}
	if gf.toolCallPolicies != nil {
		if PlaneToolCallPolicies.Validate != nil {
			if err := PlaneToolCallPolicies.Validate(gf.toolCallPolicies); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallPolicies.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneToolCallPolicies.generated.contribute(gc, source, contributorID, gf.toolCallPolicies); err != nil {
			return err
		}
	}
	if gf.toolCallFinalizers != nil {
		if PlaneToolCallFinalizers.Validate != nil {
			if err := PlaneToolCallFinalizers.Validate(gf.toolCallFinalizers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallFinalizers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneToolCallFinalizers.generated.contribute(gc, source, contributorID, gf.toolCallFinalizers); err != nil {
			return err
		}
	}
	if gf.toolCallFinalizationMaxArgsBytes > 0 {
		if PlaneToolCallFinalizationMaxArgsBytes.Validate != nil {
			if err := PlaneToolCallFinalizationMaxArgsBytes.Validate(gf.toolCallFinalizationMaxArgsBytes); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallFinalizationMaxArgsBytes.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneToolCallFinalizationMaxArgsBytes.generated.contribute(gc, source, contributorID, gf.toolCallFinalizationMaxArgsBytes); err != nil {
			return err
		}
	}
	if gf.requestTransforms != nil {
		if PlaneRequestTransforms.Validate != nil {
			if err := PlaneRequestTransforms.Validate(gf.requestTransforms); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneRequestTransforms.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneRequestTransforms.generated.contribute(gc, source, contributorID, gf.requestTransforms); err != nil {
			return err
		}
	}
	if gf.preRequestHandlers != nil {
		if PlanePreRequestHandlers.Validate != nil {
			if err := PlanePreRequestHandlers.Validate(gf.preRequestHandlers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlanePreRequestHandlers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlanePreRequestHandlers.generated.contribute(gc, source, contributorID, gf.preRequestHandlers); err != nil {
			return err
		}
	}
	if gf.routeHintProviders != nil {
		if PlaneRouteHintProviders.Validate != nil {
			if err := PlaneRouteHintProviders.Validate(gf.routeHintProviders); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneRouteHintProviders.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneRouteHintProviders.generated.contribute(gc, source, contributorID, gf.routeHintProviders); err != nil {
			return err
		}
	}
	if gf.completionGates != nil {
		if PlaneCompletionGates.Validate != nil {
			if err := PlaneCompletionGates.Validate(gf.completionGates); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompletionGates.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneCompletionGates.generated.contribute(gc, source, contributorID, gf.completionGates); err != nil {
			return err
		}
	}
	if gf.attemptTransforms != nil {
		if PlaneAttemptTransforms.Validate != nil {
			if err := PlaneAttemptTransforms.Validate(gf.attemptTransforms); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneAttemptTransforms.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneAttemptTransforms.generated.contribute(gc, source, contributorID, gf.attemptTransforms); err != nil {
			return err
		}
	}
	if gf.compactionObservers != nil {
		if PlaneCompactionObservers.Validate != nil {
			if err := PlaneCompactionObservers.Validate(gf.compactionObservers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompactionObservers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneCompactionObservers.generated.contribute(gc, source, contributorID, gf.compactionObservers); err != nil {
			return err
		}
	}
	if gf.compactionPreservers != nil {
		if PlaneCompactionPreservers.Validate != nil {
			if err := PlaneCompactionPreservers.Validate(gf.compactionPreservers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompactionPreservers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneCompactionPreservers.generated.contribute(gc, source, contributorID, gf.compactionPreservers); err != nil {
			return err
		}
	}
	if gf.secretGuards != nil {
		if PlaneSecretGuards.Validate != nil {
			if err := PlaneSecretGuards.Validate(gf.secretGuards); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneSecretGuards.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneSecretGuards.generated.contribute(gc, source, contributorID, gf.secretGuards); err != nil {
			return err
		}
	}
	if gf.localTurnHandlers != nil {
		if PlaneLocalTurnHandlers.Validate != nil {
			if err := PlaneLocalTurnHandlers.Validate(gf.localTurnHandlers); err != nil {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneLocalTurnHandlers.ID,
					Err:      fmt.Errorf("%w: %w", ErrInvalidContribution, err),
				}
			}
		}
		if err := PlaneLocalTurnHandlers.generated.contribute(gc, source, contributorID, gf.localTurnHandlers); err != nil {
			return err
		}
	}
	if gf.terminalDecisionProvider != nil {
		if !gf.terminalDecisionProviderHasID || gf.terminalDecisionProviderID == "" {
			return &AttributedError{
				PluginID: contributorID,
				PlaneID:  PlaneTerminalDecisionProvider.ID,
				Err:      fmt.Errorf("%w: frozen exclusive identity is missing", ErrInvalidContribution),
			}
		}
		if gc.terminalDecisionProviderHasID {
			return makeExclusiveConflictError(contributorID, PlaneTerminalDecisionProvider.ID, PlaneTerminalDecisionProvider.ExclusiveConflictError, gc.terminalDecisionProviderID, gf.terminalDecisionProviderID)
		}
		gc.terminalDecisionProvider = gf.terminalDecisionProvider
		gc.terminalDecisionProviderID = gf.terminalDecisionProviderID
		gc.terminalDecisionProviderHasID = true
	}
	return nil
}

// contributeCandidateMapTo contributes map-backed candidate values into dst.
func contributeCandidateMapTo(values map[string]any, dst *ContributionSet, source SourceKind, contributorID string) error {
	if len(values) == 0 || dst == nil {
		return nil
	}
	if v, ok := values[PlaneSessionOpeners.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]session.Opener)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneSessionOpeners.ID,
					Err:      fmt.Errorf("%w: expected []session.Opener, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneSessionOpeners, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneWorkspaceResolvers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]workspace.Resolver)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneWorkspaceResolvers.ID,
					Err:      fmt.Errorf("%w: expected []workspace.Resolver, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneWorkspaceResolvers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneToolCatalogFilters.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]toolcatalog.Filter)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCatalogFilters.ID,
					Err:      fmt.Errorf("%w: expected []toolcatalog.Filter, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneToolCatalogFilters, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneToolCallPolicies.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]toolpolicy.Policy)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallPolicies.ID,
					Err:      fmt.Errorf("%w: expected []toolpolicy.Policy, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneToolCallPolicies, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneToolCallFinalizers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]toolcall.Finalizer)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallFinalizers.ID,
					Err:      fmt.Errorf("%w: expected []toolcall.Finalizer, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneToolCallFinalizers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneToolCallFinalizationMaxArgsBytes.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.(int)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneToolCallFinalizationMaxArgsBytes.ID,
					Err:      fmt.Errorf("%w: expected int, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneToolCallFinalizationMaxArgsBytes, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneRequestTransforms.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]request.Transform)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneRequestTransforms.ID,
					Err:      fmt.Errorf("%w: expected []request.Transform, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneRequestTransforms, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlanePreRequestHandlers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]prerequest.Handler)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlanePreRequestHandlers.ID,
					Err:      fmt.Errorf("%w: expected []prerequest.Handler, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlanePreRequestHandlers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneRouteHintProviders.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]routehint.Provider)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneRouteHintProviders.ID,
					Err:      fmt.Errorf("%w: expected []routehint.Provider, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneRouteHintProviders, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneCompletionGates.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]completion.Gate)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompletionGates.ID,
					Err:      fmt.Errorf("%w: expected []completion.Gate, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneCompletionGates, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneAttemptTransforms.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]request.AttemptTransform)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneAttemptTransforms.ID,
					Err:      fmt.Errorf("%w: expected []request.AttemptTransform, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneAttemptTransforms, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneCompactionObservers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]compaction.Observer)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompactionObservers.ID,
					Err:      fmt.Errorf("%w: expected []compaction.Observer, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneCompactionObservers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneCompactionPreservers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]compaction.Preserver)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneCompactionPreservers.ID,
					Err:      fmt.Errorf("%w: expected []compaction.Preserver, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneCompactionPreservers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneSecretGuards.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]secretguard.Guard)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneSecretGuards.ID,
					Err:      fmt.Errorf("%w: expected []secretguard.Guard, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneSecretGuards, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneLocalTurnHandlers.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.([]localturn.Handler)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneLocalTurnHandlers.ID,
					Err:      fmt.Errorf("%w: expected []localturn.Handler, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneLocalTurnHandlers, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	if v, ok := values[PlaneTerminalDecisionProvider.ID]; ok {
		if !isNilValue(v) {
			typed, ok := v.(terminaldecision.Provider)
			if !ok {
				return &AttributedError{
					PluginID: contributorID,
					PlaneID:  PlaneTerminalDecisionProvider.ID,
					Err:      fmt.Errorf("%w: expected terminaldecision.Provider, got %T", ErrInvalidContribution, v),
				}
			}
			if err := ContributeSource(dst, PlaneTerminalDecisionProvider, source, contributorID, typed); err != nil {
				return err
			}
		}
	}
	return nil
}

func init() {
	PlaneSubmitHooks.generated = generatedAccess[[]hooks.SubmitHook]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []hooks.SubmitHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.submitHooks)
			combined, err := PlaneSubmitHooks.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.submitHooks != nil) && combined == nil {
				combined = make([]hooks.SubmitHook, 0)
			}
			gc.submitHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.SubmitHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.submitHooks)
		},
	}
	PlaneRequestPartHooks.generated = generatedAccess[[]hooks.RequestPartHook]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []hooks.RequestPartHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.requestPartHooks)
			combined, err := PlaneRequestPartHooks.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.requestPartHooks != nil) && combined == nil {
				combined = make([]hooks.RequestPartHook, 0)
			}
			gc.requestPartHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.RequestPartHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.requestPartHooks)
		},
	}
	PlaneResponsePartHooks.generated = generatedAccess[[]hooks.ResponsePartHook]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []hooks.ResponsePartHook) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.responsePartHooks)
			combined, err := PlaneResponsePartHooks.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.responsePartHooks != nil) && combined == nil {
				combined = make([]hooks.ResponsePartHook, 0)
			}
			gc.responsePartHooks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ResponsePartHook {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.responsePartHooks)
		},
	}
	PlaneToolReactors.generated = generatedAccess[[]hooks.ToolReactor]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []hooks.ToolReactor) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolReactors)
			combined, err := PlaneToolReactors.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolReactors != nil) && combined == nil {
				combined = make([]hooks.ToolReactor, 0)
			}
			gc.toolReactors = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []hooks.ToolReactor {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolReactors)
		},
	}
	PlaneSessionOpeners.generated = generatedAccess[[]session.Opener]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []session.Opener) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.sessionOpeners)
			combined, err := PlaneSessionOpeners.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.sessionOpeners != nil) && combined == nil {
				combined = make([]session.Opener, 0)
			}
			gc.sessionOpeners = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []session.Opener {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.sessionOpeners)
		},
	}
	PlaneWorkspaceResolvers.generated = generatedAccess[[]workspace.Resolver]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []workspace.Resolver) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.workspaceResolvers)
			combined, err := PlaneWorkspaceResolvers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.workspaceResolvers != nil) && combined == nil {
				combined = make([]workspace.Resolver, 0)
			}
			gc.workspaceResolvers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []workspace.Resolver {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.workspaceResolvers)
		},
	}
	PlaneToolCatalogFilters.generated = generatedAccess[[]toolcatalog.Filter]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []toolcatalog.Filter) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCatalogFilters)
			combined, err := PlaneToolCatalogFilters.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCatalogFilters != nil) && combined == nil {
				combined = make([]toolcatalog.Filter, 0)
			}
			gc.toolCatalogFilters = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolcatalog.Filter {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCatalogFilters)
		},
	}
	PlaneToolCallPolicies.generated = generatedAccess[[]toolpolicy.Policy]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []toolpolicy.Policy) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCallPolicies)
			combined, err := PlaneToolCallPolicies.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCallPolicies != nil) && combined == nil {
				combined = make([]toolpolicy.Policy, 0)
			}
			gc.toolCallPolicies = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolpolicy.Policy {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCallPolicies)
		},
	}
	PlaneToolCallFinalizers.generated = generatedAccess[[]toolcall.Finalizer]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []toolcall.Finalizer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.toolCallFinalizers)
			combined, err := PlaneToolCallFinalizers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.toolCallFinalizers != nil) && combined == nil {
				combined = make([]toolcall.Finalizer, 0)
			}
			gc.toolCallFinalizers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []toolcall.Finalizer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.toolCallFinalizers)
		},
	}
	PlaneToolCallFinalizationMaxArgsBytes.generated = generatedAccess[int]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v int) error {
			combined, err := PlaneToolCallFinalizationMaxArgsBytes.Combine(source, gc.toolCallFinalizationMaxArgsBytes, v)
			if err != nil {
				return err
			}
			gc.toolCallFinalizationMaxArgsBytes = combined
			return nil
		},
		get: func(gf *generatedFrozen) int {
			if gf == nil {
				return 0
			}
			return gf.toolCallFinalizationMaxArgsBytes
		},
	}
	PlaneRequestTransforms.generated = generatedAccess[[]request.Transform]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []request.Transform) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.requestTransforms)
			combined, err := PlaneRequestTransforms.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.requestTransforms != nil) && combined == nil {
				combined = make([]request.Transform, 0)
			}
			gc.requestTransforms = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []request.Transform {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.requestTransforms)
		},
	}
	PlanePreRequestHandlers.generated = generatedAccess[[]prerequest.Handler]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []prerequest.Handler) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.preRequestHandlers)
			combined, err := PlanePreRequestHandlers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.preRequestHandlers != nil) && combined == nil {
				combined = make([]prerequest.Handler, 0)
			}
			gc.preRequestHandlers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []prerequest.Handler {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.preRequestHandlers)
		},
	}
	PlaneRouteHintProviders.generated = generatedAccess[[]routehint.Provider]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []routehint.Provider) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.routeHintProviders)
			combined, err := PlaneRouteHintProviders.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.routeHintProviders != nil) && combined == nil {
				combined = make([]routehint.Provider, 0)
			}
			gc.routeHintProviders = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []routehint.Provider {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.routeHintProviders)
		},
	}
	PlaneCompletionGates.generated = generatedAccess[[]completion.Gate]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []completion.Gate) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.completionGates)
			combined, err := PlaneCompletionGates.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.completionGates != nil) && combined == nil {
				combined = make([]completion.Gate, 0)
			}
			gc.completionGates = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []completion.Gate {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.completionGates)
		},
	}
	PlaneAttemptTransforms.generated = generatedAccess[[]request.AttemptTransform]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []request.AttemptTransform) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.attemptTransforms)
			combined, err := PlaneAttemptTransforms.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.attemptTransforms != nil) && combined == nil {
				combined = make([]request.AttemptTransform, 0)
			}
			gc.attemptTransforms = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []request.AttemptTransform {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.attemptTransforms)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneAttemptTransforms.Identity(gf.attemptTransforms)
		},
	}
	PlaneStreamObserverFactories.generated = generatedAccess[[]response.StreamObserverFactory]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []response.StreamObserverFactory) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.streamObserverFactories)
			combined, err := PlaneStreamObserverFactories.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.streamObserverFactories != nil) && combined == nil {
				combined = make([]response.StreamObserverFactory, 0)
			}
			gc.streamObserverFactories = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []response.StreamObserverFactory {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.streamObserverFactories)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneStreamObserverFactories.Identity(gf.streamObserverFactories)
		},
	}
	PlaneTrafficObservers.generated = generatedAccess[[]traffic.Observer]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []traffic.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.trafficObservers)
			combined, err := PlaneTrafficObservers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.trafficObservers != nil) && combined == nil {
				combined = make([]traffic.Observer, 0)
			}
			gc.trafficObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.trafficObservers)
		},
	}
	PlaneUsageObservers.generated = generatedAccess[[]usage.Observer]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []usage.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.usageObservers)
			combined, err := PlaneUsageObservers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.usageObservers != nil) && combined == nil {
				combined = make([]usage.Observer, 0)
			}
			gc.usageObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []usage.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.usageObservers)
		},
	}
	PlaneRawCaptureSinks.generated = generatedAccess[[]traffic.RawCaptureSink]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []traffic.RawCaptureSink) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.rawCaptureSinks)
			combined, err := PlaneRawCaptureSinks.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.rawCaptureSinks != nil) && combined == nil {
				combined = make([]traffic.RawCaptureSink, 0)
			}
			gc.rawCaptureSinks = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.RawCaptureSink {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.rawCaptureSinks)
		},
	}
	PlaneTrafficRedactors.generated = generatedAccess[[]traffic.Redactor]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []traffic.Redactor) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.trafficRedactors)
			combined, err := PlaneTrafficRedactors.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.trafficRedactors != nil) && combined == nil {
				combined = make([]traffic.Redactor, 0)
			}
			gc.trafficRedactors = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []traffic.Redactor {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.trafficRedactors)
		},
	}
	PlaneCompactionObservers.generated = generatedAccess[[]compaction.Observer]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []compaction.Observer) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.compactionObservers)
			combined, err := PlaneCompactionObservers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.compactionObservers != nil) && combined == nil {
				combined = make([]compaction.Observer, 0)
			}
			gc.compactionObservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Observer {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.compactionObservers)
		},
	}
	PlaneCompactionPreservers.generated = generatedAccess[[]compaction.Preserver]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []compaction.Preserver) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.compactionPreservers)
			combined, err := PlaneCompactionPreservers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.compactionPreservers != nil) && combined == nil {
				combined = make([]compaction.Preserver, 0)
			}
			gc.compactionPreservers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []compaction.Preserver {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.compactionPreservers)
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return PlaneCompactionPreservers.Identity(gf.compactionPreservers)
		},
	}
	PlaneSecretGuards.generated = generatedAccess[[]secretguard.Guard]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []secretguard.Guard) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.secretGuards)
			combined, err := PlaneSecretGuards.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.secretGuards != nil) && combined == nil {
				combined = make([]secretguard.Guard, 0)
			}
			gc.secretGuards = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []secretguard.Guard {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.secretGuards)
		},
	}
	PlaneLocalTurnHandlers.generated = generatedAccess[[]localturn.Handler]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v []localturn.Handler) error {
			incoming := cloneSlice(v)
			current := cloneSlice(gc.localTurnHandlers)
			combined, err := PlaneLocalTurnHandlers.Combine(source, current, incoming)
			if err != nil {
				return err
			}
			if (v != nil || gc.localTurnHandlers != nil) && combined == nil {
				combined = make([]localturn.Handler, 0)
			}
			gc.localTurnHandlers = cloneSlice(combined)
			return nil
		},
		get: func(gf *generatedFrozen) []localturn.Handler {
			if gf == nil {
				return nil
			}
			return cloneSlice(gf.localTurnHandlers)
		},
	}
	PlaneTerminalDecisionProvider.generated = generatedAccess[terminaldecision.Provider]{
		contribute: func(gc *generatedContributions, source SourceKind, pluginID string, v terminaldecision.Provider) error {
			combined, err := PlaneTerminalDecisionProvider.Combine(source, gc.terminalDecisionProvider, v)
			if err != nil {
				return err
			}
			gc.terminalDecisionProvider = combined
			id, hasID := PlaneTerminalDecisionProvider.Identity(v)
			gc.terminalDecisionProviderID = id
			gc.terminalDecisionProviderHasID = hasID
			return nil
		},
		get: func(gf *generatedFrozen) terminaldecision.Provider {
			if gf == nil {
				return nil
			}
			return gf.terminalDecisionProvider
		},
		identity: func(gf *generatedFrozen) (string, bool) {
			if gf == nil {
				return "", false
			}
			return gf.terminalDecisionProviderID, gf.terminalDecisionProviderHasID
		},
	}
}

// RequestExecutionView is an immutable borrowed view over request-materialized planes.
// Its returned slices must not be mutated.
type RequestExecutionView struct {
	frozen FrozenPlaneSet
}

// RequestExecution constructs a RequestExecutionView over the request-materialized planes in in.
func RequestExecution(in FrozenPlaneSet) RequestExecutionView {
	return RequestExecutionView{frozen: in}
}

// ToolCallPolicies returns the request-materialized ToolCallPolicies without cloning.
// The returned slice is immutable borrowed storage and MUST NOT be mutated.
func (v RequestExecutionView) ToolCallPolicies() []toolpolicy.Policy {
	if v.frozen.frozen == nil {
		return nil
	}
	return v.frozen.frozen.toolCallPolicies
}

// ToolCallFinalizers returns the request-materialized ToolCallFinalizers without cloning.
// The returned slice is immutable borrowed storage and MUST NOT be mutated.
func (v RequestExecutionView) ToolCallFinalizers() []toolcall.Finalizer {
	if v.frozen.frozen == nil {
		return nil
	}
	return v.frozen.frozen.toolCallFinalizers
}

// SecretGuards returns the request-materialized SecretGuards without cloning.
// The returned slice is immutable borrowed storage and MUST NOT be mutated.
func (v RequestExecutionView) SecretGuards() []secretguard.Guard {
	if v.frozen.frozen == nil {
		return nil
	}
	return v.frozen.frozen.secretGuards
}

// LocalTurnHandlers returns the request-materialized LocalTurnHandlers without cloning.
// The returned slice is immutable borrowed storage and MUST NOT be mutated.
func (v RequestExecutionView) LocalTurnHandlers() []localturn.Handler {
	if v.frozen.frozen == nil {
		return nil
	}
	return v.frozen.frozen.localTurnHandlers
}

// BindAttemptTransforms replaces AttemptTransforms under SourceGenerationBinder semantics.
func (s *ContributionSet) BindAttemptTransforms(contributorID string, v []request.AttemptTransform) error {
	return ContributeSource(s, PlaneAttemptTransforms, SourceGenerationBinder, contributorID, v)
}

// ReplaceAttemptTransforms replaces AttemptTransforms under SourceGenerationBinder semantics.
func (s *ContributionSet) ReplaceAttemptTransforms(contributorID string, v []request.AttemptTransform) error {
	return ContributeSource(s, PlaneAttemptTransforms, SourceGenerationBinder, contributorID, v)
}

// BindStreamObserverFactories replaces StreamObserverFactories under SourceGenerationBinder semantics.
func (s *ContributionSet) BindStreamObserverFactories(contributorID string, v []response.StreamObserverFactory) error {
	return ContributeSource(s, PlaneStreamObserverFactories, SourceGenerationBinder, contributorID, v)
}

// ReplaceStreamObserverFactories replaces StreamObserverFactories under SourceGenerationBinder semantics.
func (s *ContributionSet) ReplaceStreamObserverFactories(contributorID string, v []response.StreamObserverFactory) error {
	return ContributeSource(s, PlaneStreamObserverFactories, SourceGenerationBinder, contributorID, v)
}

// BindCompactionPreservers replaces CompactionPreservers under SourceGenerationBinder semantics.
func (s *ContributionSet) BindCompactionPreservers(contributorID string, v []compaction.Preserver) error {
	return ContributeSource(s, PlaneCompactionPreservers, SourceGenerationBinder, contributorID, v)
}

// ReplaceCompactionPreservers replaces CompactionPreservers under SourceGenerationBinder semantics.
func (s *ContributionSet) ReplaceCompactionPreservers(contributorID string, v []compaction.Preserver) error {
	return ContributeSource(s, PlaneCompactionPreservers, SourceGenerationBinder, contributorID, v)
}

// ProjectDiagnostics projects diagnostic occupants and privileges from a frozen plane set.
func ProjectDiagnostics(in FrozenPlaneSet) []DiagnosticPlaneProjection {
	if in.IsZero() {
		return nil
	}
	gf := in.frozen
	if gf == nil && (in.values != nil || in.identities != nil) {
		cset := in.ToContributions()
		gf = cset.Freeze().frozen
	}
	if gf == nil {
		return nil
	}
	var projections []DiagnosticPlaneProjection

	// Project PlaneSubmitHooks
	{
		val := gf.submitHooks
		occ := PlaneSubmitHooks.MaterializeOccupants(val)
		priv := PlaneSubmitHooks.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneSubmitHooks.ID,
				StageID:       PlaneSubmitHooks.Diagnostics.StageID,
				CoalesceGroup: PlaneSubmitHooks.Diagnostics.CoalesceGroup,
				Order:         PlaneSubmitHooks.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneRequestPartHooks
	{
		val := gf.requestPartHooks
		occ := PlaneRequestPartHooks.MaterializeOccupants(val)
		priv := PlaneRequestPartHooks.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneRequestPartHooks.ID,
				StageID:       PlaneRequestPartHooks.Diagnostics.StageID,
				CoalesceGroup: PlaneRequestPartHooks.Diagnostics.CoalesceGroup,
				Order:         PlaneRequestPartHooks.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneResponsePartHooks
	{
		val := gf.responsePartHooks
		occ := PlaneResponsePartHooks.MaterializeOccupants(val)
		priv := PlaneResponsePartHooks.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneResponsePartHooks.ID,
				StageID:       PlaneResponsePartHooks.Diagnostics.StageID,
				CoalesceGroup: PlaneResponsePartHooks.Diagnostics.CoalesceGroup,
				Order:         PlaneResponsePartHooks.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneToolReactors
	{
		val := gf.toolReactors
		occ := PlaneToolReactors.MaterializeOccupants(val)
		priv := PlaneToolReactors.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneToolReactors.ID,
				StageID:       PlaneToolReactors.Diagnostics.StageID,
				CoalesceGroup: PlaneToolReactors.Diagnostics.CoalesceGroup,
				Order:         PlaneToolReactors.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneSessionOpeners
	{
		val := gf.sessionOpeners
		occ := PlaneSessionOpeners.MaterializeOccupants(val)
		priv := PlaneSessionOpeners.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneSessionOpeners.ID,
				StageID:       PlaneSessionOpeners.Diagnostics.StageID,
				CoalesceGroup: PlaneSessionOpeners.Diagnostics.CoalesceGroup,
				Order:         PlaneSessionOpeners.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneWorkspaceResolvers
	{
		val := gf.workspaceResolvers
		occ := PlaneWorkspaceResolvers.MaterializeOccupants(val)
		priv := PlaneWorkspaceResolvers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneWorkspaceResolvers.ID,
				StageID:       PlaneWorkspaceResolvers.Diagnostics.StageID,
				CoalesceGroup: PlaneWorkspaceResolvers.Diagnostics.CoalesceGroup,
				Order:         PlaneWorkspaceResolvers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneToolCatalogFilters
	{
		val := gf.toolCatalogFilters
		occ := PlaneToolCatalogFilters.MaterializeOccupants(val)
		priv := PlaneToolCatalogFilters.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneToolCatalogFilters.ID,
				StageID:       PlaneToolCatalogFilters.Diagnostics.StageID,
				CoalesceGroup: PlaneToolCatalogFilters.Diagnostics.CoalesceGroup,
				Order:         PlaneToolCatalogFilters.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneToolCallPolicies
	{
		val := gf.toolCallPolicies
		occ := PlaneToolCallPolicies.MaterializeOccupants(val)
		priv := PlaneToolCallPolicies.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneToolCallPolicies.ID,
				StageID:       PlaneToolCallPolicies.Diagnostics.StageID,
				CoalesceGroup: PlaneToolCallPolicies.Diagnostics.CoalesceGroup,
				Order:         PlaneToolCallPolicies.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneToolCallFinalizers
	{
		val := gf.toolCallFinalizers
		occ := PlaneToolCallFinalizers.MaterializeOccupants(val)
		priv := PlaneToolCallFinalizers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneToolCallFinalizers.ID,
				StageID:       PlaneToolCallFinalizers.Diagnostics.StageID,
				CoalesceGroup: PlaneToolCallFinalizers.Diagnostics.CoalesceGroup,
				Order:         PlaneToolCallFinalizers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneRequestTransforms
	{
		val := gf.requestTransforms
		occ := PlaneRequestTransforms.MaterializeOccupants(val)
		priv := PlaneRequestTransforms.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneRequestTransforms.ID,
				StageID:       PlaneRequestTransforms.Diagnostics.StageID,
				CoalesceGroup: PlaneRequestTransforms.Diagnostics.CoalesceGroup,
				Order:         PlaneRequestTransforms.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlanePreRequestHandlers
	{
		val := gf.preRequestHandlers
		occ := PlanePreRequestHandlers.MaterializeOccupants(val)
		priv := PlanePreRequestHandlers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlanePreRequestHandlers.ID,
				StageID:       PlanePreRequestHandlers.Diagnostics.StageID,
				CoalesceGroup: PlanePreRequestHandlers.Diagnostics.CoalesceGroup,
				Order:         PlanePreRequestHandlers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneRouteHintProviders
	{
		val := gf.routeHintProviders
		occ := PlaneRouteHintProviders.MaterializeOccupants(val)
		priv := PlaneRouteHintProviders.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneRouteHintProviders.ID,
				StageID:       PlaneRouteHintProviders.Diagnostics.StageID,
				CoalesceGroup: PlaneRouteHintProviders.Diagnostics.CoalesceGroup,
				Order:         PlaneRouteHintProviders.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneCompletionGates
	{
		val := gf.completionGates
		occ := PlaneCompletionGates.MaterializeOccupants(val)
		priv := PlaneCompletionGates.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneCompletionGates.ID,
				StageID:       PlaneCompletionGates.Diagnostics.StageID,
				CoalesceGroup: PlaneCompletionGates.Diagnostics.CoalesceGroup,
				Order:         PlaneCompletionGates.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneAttemptTransforms
	{
		val := gf.attemptTransforms
		occ := PlaneAttemptTransforms.MaterializeOccupants(val)
		priv := PlaneAttemptTransforms.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneAttemptTransforms.ID,
				StageID:       PlaneAttemptTransforms.Diagnostics.StageID,
				CoalesceGroup: PlaneAttemptTransforms.Diagnostics.CoalesceGroup,
				Order:         PlaneAttemptTransforms.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneStreamObserverFactories
	{
		val := gf.streamObserverFactories
		occ := PlaneStreamObserverFactories.MaterializeOccupants(val)
		priv := PlaneStreamObserverFactories.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneStreamObserverFactories.ID,
				StageID:       PlaneStreamObserverFactories.Diagnostics.StageID,
				CoalesceGroup: PlaneStreamObserverFactories.Diagnostics.CoalesceGroup,
				Order:         PlaneStreamObserverFactories.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneTrafficObservers
	{
		val := gf.trafficObservers
		occ := PlaneTrafficObservers.MaterializeOccupants(val)
		priv := PlaneTrafficObservers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneTrafficObservers.ID,
				StageID:       PlaneTrafficObservers.Diagnostics.StageID,
				CoalesceGroup: PlaneTrafficObservers.Diagnostics.CoalesceGroup,
				Order:         PlaneTrafficObservers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneUsageObservers
	{
		val := gf.usageObservers
		occ := PlaneUsageObservers.MaterializeOccupants(val)
		priv := PlaneUsageObservers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneUsageObservers.ID,
				StageID:       PlaneUsageObservers.Diagnostics.StageID,
				CoalesceGroup: PlaneUsageObservers.Diagnostics.CoalesceGroup,
				Order:         PlaneUsageObservers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneRawCaptureSinks
	{
		val := gf.rawCaptureSinks
		occ := PlaneRawCaptureSinks.MaterializeOccupants(val)
		priv := PlaneRawCaptureSinks.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneRawCaptureSinks.ID,
				StageID:       PlaneRawCaptureSinks.Diagnostics.StageID,
				CoalesceGroup: PlaneRawCaptureSinks.Diagnostics.CoalesceGroup,
				Order:         PlaneRawCaptureSinks.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneTrafficRedactors
	{
		val := gf.trafficRedactors
		occ := PlaneTrafficRedactors.MaterializeOccupants(val)
		priv := PlaneTrafficRedactors.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneTrafficRedactors.ID,
				StageID:       PlaneTrafficRedactors.Diagnostics.StageID,
				CoalesceGroup: PlaneTrafficRedactors.Diagnostics.CoalesceGroup,
				Order:         PlaneTrafficRedactors.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneSecretGuards
	{
		val := gf.secretGuards
		occ := PlaneSecretGuards.MaterializeOccupants(val)
		priv := PlaneSecretGuards.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneSecretGuards.ID,
				StageID:       PlaneSecretGuards.Diagnostics.StageID,
				CoalesceGroup: PlaneSecretGuards.Diagnostics.CoalesceGroup,
				Order:         PlaneSecretGuards.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	// Project PlaneLocalTurnHandlers
	{
		val := gf.localTurnHandlers
		occ := PlaneLocalTurnHandlers.MaterializeOccupants(val)
		priv := PlaneLocalTurnHandlers.ProjectPrivileges(val)
		if len(occ) > 0 || len(priv.Flags) > 0 {
			var occCopy []DiagnosticOccupant
			if len(occ) > 0 {
				occCopy = make([]DiagnosticOccupant, len(occ))
				for i := 0; i < len(occ); i++ {
					o := occ[i]
					var pCopy []string
					if len(o.Privileges) > 0 {
						pCopy = append([]string(nil), o.Privileges...)
					}
					occCopy[i] = DiagnosticOccupant{
						Label:      o.Label,
						PluginID:   o.PluginID,
						Privileges: pCopy,
					}
				}
			}
			var privCopy []string
			if len(priv.Flags) > 0 {
				privCopy = append([]string(nil), priv.Flags...)
			}
			projections = append(projections, DiagnosticPlaneProjection{
				PlaneID:       PlaneLocalTurnHandlers.ID,
				StageID:       PlaneLocalTurnHandlers.Diagnostics.StageID,
				CoalesceGroup: PlaneLocalTurnHandlers.Diagnostics.CoalesceGroup,
				Order:         PlaneLocalTurnHandlers.Diagnostics.Order,
				Occupants:     occCopy,
				Privileges:    PrivilegeProjection{Flags: privCopy},
			})
		}
	}

	return projections
}
