package archtest

import (
	"bytes"
	"fmt"
	"strings"
)

func canonicalPolicyVar(p planeInfo) string {
	return fmt.Sprintf("canonical%sPolicy", p.varName)
}

func canonicalAccessVar(p planeInfo) string {
	return fmt.Sprintf("canonical%sAccess", p.varName)
}

func generatePlanesCode(planes []planeInfo, sdkImports []string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.\n\n")
	buf.WriteString("package feature\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"errors\"\n")
	buf.WriteString("\t\"fmt\"\n\n")
	for _, imp := range sdkImports {
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	// 1. generatedContributions struct
	buf.WriteString("// generatedContributions holds typed contribution storage for all declared feature planes.\n")
	buf.WriteString("type generatedContributions struct {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 2. generatedFrozen struct
	buf.WriteString("// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.\n")
	buf.WriteString("type generatedFrozen struct {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 3. newGeneratedContributions constructor
	buf.WriteString("// newGeneratedContributions constructs a new empty generatedContributions.\n")
	buf.WriteString("func newGeneratedContributions() *generatedContributions {\n")
	buf.WriteString("\treturn &generatedContributions{}\n")
	buf.WriteString("}\n\n")

	// 4. clone method
	buf.WriteString("func (gc *generatedContributions) clone() *generatedContributions {\n")
	buf.WriteString("\tif gc == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tnext := newGeneratedContributions()\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\tnext.%s = cloneSlice(gc.%s)\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\tnext.%s = gc.%s\n", p.fieldName, p.fieldName)
		}
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\tnext.%sID = gc.%sID\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\tnext.%sHasID = gc.%sHasID\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\treturn next\n")
	buf.WriteString("}\n\n")

	// 5. freeze method
	buf.WriteString("func (gc *generatedContributions) freeze() *generatedFrozen {\n")
	buf.WriteString("\tif gc == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tgf := &generatedFrozen{\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t%s: cloneSlice(gc.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t%s: gc.%s,\n", p.fieldName, p.fieldName)
		}
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\t\t%sID: gc.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t%sHasID: gc.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn gf\n")
	buf.WriteString("}\n\n")

	// 6. toContributions method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) toContributions() *generatedContributions {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn newGeneratedContributions()\n\t}\n")
	buf.WriteString("\tgc := newGeneratedContributions()\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\tgc.%s = cloneSlice(gf.%s)\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\tgc.%s = gf.%s\n", p.fieldName, p.fieldName)
		}
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\tgc.%sID = gf.%sID\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\tgc.%sHasID = gf.%sHasID\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\treturn gc\n")
	buf.WriteString("}\n\n")

	// 6b. freezeRequest method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) freezeRequest() *generatedFrozen {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tnext := &generatedFrozen{\n")
	for _, p := range planes {
		policyVar := canonicalPolicyVar(p)
		if p.hasRequestMaterializer {
			if strings.HasPrefix(p.typeExpr, "[]") {
				fmt.Fprintf(&buf, "\t\t%s: materializeRequestSlice(gf.%s, %s.requestMaterializer),\n", p.fieldName, p.fieldName, policyVar)
			} else {
				fmt.Fprintf(&buf, "\t\t%s: %s.requestMaterializer(gf.%s),\n", p.fieldName, policyVar, p.fieldName)
			}
		} else if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t%s: cloneSlice(gf.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t%s: gf.%s,\n", p.fieldName, p.fieldName)
		}
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\t\t%sID: gf.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t%sHasID: gf.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn next\n")
	buf.WriteString("}\n\n")

	// 6c. clone method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) clone() *generatedFrozen {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tnext := &generatedFrozen{\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t%s: cloneSlice(gf.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t%s: gf.%s,\n", p.fieldName, p.fieldName)
		}
		if p.hasIdentity {
			fmt.Fprintf(&buf, "\t\t%sID: gf.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t%sHasID: gf.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn next\n")
	buf.WriteString("}\n\n")

	// 6d. validate method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) validate() error {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn nil\n\t}\n")
	for _, p := range planes {
		policyVar := canonicalPolicyVar(p)
		if strings.HasPrefix(p.typeExpr, "[]") {
			if p.hasIdentity {
				fmt.Fprintf(&buf, "\tif gf.%s == nil {\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\tif gf.%sHasID || gf.%sID != \"\" {\n", p.fieldName, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\treturn newPlaneValidationError(%s.planeID, errors.New(\"malformed metadata without value\"))\n", policyVar)
				fmt.Fprintf(&buf, "\t\t}\n")
				fmt.Fprintf(&buf, "\t} else {\n")
				fmt.Fprintf(&buf, "\t\tif %s.validate != nil {\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\tif err := %s.validate(gf.%s); err != nil {\n", policyVar, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\t}\n")
				fmt.Fprintf(&buf, "\t\t}\n")
				fmt.Fprintf(&buf, "\t\tif !gf.%sHasID {\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tif gf.%sID != \"\" || len(gf.%s) > 0 {\n", p.fieldName, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, errors.New(\"missing cached identity\"))\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\t}\n")
				fmt.Fprintf(&buf, "\t\t} else {\n")
				fmt.Fprintf(&buf, "\t\t\tif gf.%sID == \"\" {\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, errors.New(\"missing cached identity\"))\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\t}\n")
				if p.hasValidateIdentity {
					fmt.Fprintf(&buf, "\t\t\tif err := %s.validateIdentity(gf.%sID); err != nil {\n", policyVar, p.fieldName)
					fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
					fmt.Fprintf(&buf, "\t\t\t}\n")
				}
				fmt.Fprintf(&buf, "\t\t}\n")
				fmt.Fprintf(&buf, "\t}\n")
			} else {
				fmt.Fprintf(&buf, "\tif gf.%s != nil {\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\tif %s.validate != nil {\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\tif err := %s.validate(gf.%s); err != nil {\n", policyVar, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
				fmt.Fprintf(&buf, "\t\t\t}\n")
				fmt.Fprintf(&buf, "\t\t}\n")
				fmt.Fprintf(&buf, "\t}\n")
			}
		} else if p.typeExpr == "int" {
			fmt.Fprintf(&buf, "\tif gf.%s < 0 {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\treturn newPlaneValidationError(%s.planeID, fmt.Errorf(\"must be >= 0, got %%d\", gf.%s))\n", policyVar, p.fieldName)
			fmt.Fprintf(&buf, "\t}\n")
			fmt.Fprintf(&buf, "\tif gf.%s > 0 && %s.validate != nil {\n", p.fieldName, policyVar)
			fmt.Fprintf(&buf, "\t\tif err := %s.validate(gf.%s); err != nil {\n", policyVar, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t}\n")
		} else if p.isExclusive {
			fmt.Fprintf(&buf, "\tif gf.%s == nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif gf.%sHasID || gf.%sID != \"\" {\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\treturn newPlaneValidationError(%s.planeID, errors.New(\"malformed metadata without value\"))\n", policyVar)
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t} else {\n")
			fmt.Fprintf(&buf, "\t\tif !gf.%sHasID || gf.%sID == \"\" {\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\treturn newPlaneValidationError(%s.planeID, errors.New(\"missing cached identity\"))\n", policyVar)
			fmt.Fprintf(&buf, "\t\t}\n")
			if p.hasValidateIdentity {
				fmt.Fprintf(&buf, "\t\tif err := %s.validateIdentity(gf.%sID); err != nil {\n", policyVar, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
				fmt.Fprintf(&buf, "\t\t}\n")
			}
			fmt.Fprintf(&buf, "\t}\n")
		} else {
			fmt.Fprintf(&buf, "\tif gf.%s != nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif %s.validate != nil {\n", policyVar)
			fmt.Fprintf(&buf, "\t\t\tif err := %s.validate(gf.%s); err != nil {\n", policyVar, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\treturn newPlaneValidationError(%s.planeID, err)\n", policyVar)
			fmt.Fprintf(&buf, "\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t}\n")
		}
	}
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	// 6b. checkSourceAdmission and checkCandidateSourceAdmission methods on generatedFrozen
	emitCheckSourceAdmission(&buf, planes)
	emitCheckCandidateSourceAdmission(&buf, planes)

	// 7. contributeCandidateTo method on generatedFrozen
	emitContributeCandidateTo(&buf, planes)

	// 7b. replayAllPlanesTo method on generatedFrozen
	emitReplayAllPlanesTo(&buf, planes)

	// 7c. hasIdentityReplayRule method on generatedFrozen
	buf.WriteString("// hasIdentityReplayRule reports whether gf contains a present identity-bearing plane\n")
	buf.WriteString("// whose declared rule for source matches the given combination rule.\n")
	buf.WriteString("func (gf *generatedFrozen) hasIdentityReplayRule(source SourceKind, rule Combination) (string, bool) {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn \"\", false\n\t}\n")
	for _, p := range planes {
		if !p.hasIdentity {
			continue
		}
		policyVar := canonicalPolicyVar(p)
		fmt.Fprintf(&buf, "\tif %s.rules.RuleFor(source) == rule {\n", policyVar)
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\tif len(gf.%s) > 0 {\n\t\t\treturn %s.planeID, true\n\t\t}\n", p.fieldName, policyVar)
		} else if p.typeExpr == "int" {
			fmt.Fprintf(&buf, "\t\tif gf.%s > 0 {\n\t\t\treturn %s.planeID, true\n\t\t}\n", p.fieldName, policyVar)
		} else {
			fmt.Fprintf(&buf, "\t\tif !isNilValue(gf.%s) {\n\t\t\treturn %s.planeID, true\n\t\t}\n", p.fieldName, policyVar)
		}
		buf.WriteString("\t}\n")
	}
	buf.WriteString("\treturn \"\", false\n")
	buf.WriteString("}\n\n")

	// 8b. canonical policy and access declarations
	buf.WriteString("// Canonical plane policies and access handles captured once at package init.\n")
	buf.WriteString("var (\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s *generatedPolicy[%s]\n", canonicalPolicyVar(p), p.typeExpr)
		fmt.Fprintf(&buf, "\t%s generatedAccess[%s]\n", canonicalAccessVar(p), p.typeExpr)
	}
	buf.WriteString(")\n\n")

	// 9. init() binding closures
	buf.WriteString("func init() {\n")
	for _, p := range planes {
		policyVar := canonicalPolicyVar(p)
		accessVar := canonicalAccessVar(p)

		// 1. Capture canonical policy first before any closures
		fmt.Fprintf(&buf, "\t%s = &generatedPolicy[%s]{\n", policyVar, p.typeExpr)
		fmt.Fprintf(&buf, "\t\tplaneID:                %s.ID,\n", p.varName)
		fmt.Fprintf(&buf, "\t\trules:                  %s.Rules,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tnilPolicy:              %s.NilPolicy,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tisNil:                  %s.IsNil,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tvalidate:               %s.Validate,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tvalidateIdentity:       %s.ValidateIdentity,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tcombine:                %s.Combine,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tidentity:               %s.Identity,\n", p.varName)
		fmt.Fprintf(&buf, "\t\texclusiveConflictError: %s.ExclusiveConflictError,\n", p.varName)
		fmt.Fprintf(&buf, "\t\trequestMaterializer:    %s.RequestMaterializer,\n", p.varName)
		fmt.Fprintf(&buf, "\t\trequestBorrow:          %s.RequestBorrow,\n", p.varName)
		fmt.Fprintf(&buf, "\t\thookTarget:             %s.HookTarget,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tdiagStageID:            %s.Diagnostics.StageID,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tdiagCoalesceGroup:      %s.Diagnostics.CoalesceGroup,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tdiagOrder:              %s.Diagnostics.Order,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tdiagMaterialize:        %s.Diagnostics.Materialize,\n", p.varName)
		fmt.Fprintf(&buf, "\t\tdiagPrivileges:         %s.Diagnostics.Privileges,\n", p.varName)
		buf.WriteString("\t}\n")

		// 2. Access closure definition using canonicalPolicyVar
		fmt.Fprintf(&buf, "\t%s = generatedAccess[%s]{\n", accessVar, p.typeExpr)
		fmt.Fprintf(&buf, "\t\tpolicy: %s,\n", policyVar)
		fmt.Fprintf(&buf, "\t\tcontribute: func(gc *generatedContributions, source SourceKind, pluginID string, v %s) error {\n", p.typeExpr)
		if strings.HasPrefix(p.typeExpr, "[]") {
			buf.WriteString("\t\t\tincoming := cloneSlice(v)\n")
			fmt.Fprintf(&buf, "\t\t\tcurrent := cloneSlice(gc.%s)\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.combine(source, current, incoming)\n", policyVar)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tif (v != nil || gc.%s != nil) && combined == nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\tcombined = make(%s, 0)\n", p.typeExpr)
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = cloneSlice(combined)\n", p.fieldName)
			if p.hasIdentity {
				fmt.Fprintf(&buf, "\t\t\tid, hasID := %s.identity(gc.%s)\n", policyVar, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sID = id\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sHasID = hasID\n", p.fieldName)
			}
		} else {
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.combine(source, gc.%s, v)\n", policyVar, p.fieldName)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = combined\n", p.fieldName)
			if p.hasIdentity {
				fmt.Fprintf(&buf, "\t\t\tid, hasID := %s.identity(gc.%s)\n", policyVar, p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sID = id\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sHasID = hasID\n", p.fieldName)
			}
		}
		buf.WriteString("\t\t\treturn nil\n")
		buf.WriteString("\t\t},\n")

		// get closure
		fmt.Fprintf(&buf, "\t\tget: func(gf *generatedFrozen) %s {\n", p.typeExpr)
		buf.WriteString("\t\t\tif gf == nil {\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			buf.WriteString("\t\t\t\treturn nil\n")
		} else if p.typeExpr == "int" {
			buf.WriteString("\t\t\t\treturn 0\n")
		} else {
			buf.WriteString("\t\t\t\treturn nil\n")
		}
		buf.WriteString("\t\t\t}\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\treturn cloneSlice(gf.%s)\n", p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\treturn gf.%s\n", p.fieldName)
		}
		buf.WriteString("\t\t},\n")

		// identity closure
		if p.hasIdentity {
			buf.WriteString("\t\tidentity: func(gf *generatedFrozen) (string, bool) {\n")
			buf.WriteString("\t\t\tif gf == nil {\n")
			buf.WriteString("\t\t\t\treturn \"\", false\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\treturn gf.%sID, gf.%sHasID\n", p.fieldName, p.fieldName)
			buf.WriteString("\t\t},\n")
		}

		buf.WriteString("\t}\n")
		fmt.Fprintf(&buf, "\t%s.generated = %s\n\n", p.varName, accessVar)
	}
	buf.WriteString("}\n\n")

	// 9b. HookConfig and ProjectHookConfig
	emitHookConfig(&buf, planes)

	// 10. RequestExecutionView and methods
	emitRequestExecutionView(&buf, planes)

	// 11. Generation binder methods on *ContributionSet for replace-by-identity planes
	emitGenerationBinderMethods(&buf, planes)

	// 12. ProjectDiagnostics function
	emitProjectDiagnostics(&buf, planes)

	return buf.Bytes(), nil
}
