package archtest

import (
	"bytes"
	"fmt"
	"strings"
)

func generatePlanesCode(planes []planeInfo, sdkImports []string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.\n\n")
	buf.WriteString("package feature\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"fmt\"\n\n")
	for _, imp := range sdkImports {
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	// 1. generatedContributions struct
	buf.WriteString("// generatedContributions holds typed contribution storage for all declared feature planes.\n")
	buf.WriteString("type generatedContributions struct {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 2. generatedFrozen struct
	buf.WriteString("// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.\n")
	buf.WriteString("type generatedFrozen struct {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 3. newGeneratedContributions constructor
	buf.WriteString("// newGeneratedContributions constructs a new empty generatedContributions.\n")
	buf.WriteString("func newGeneratedContributions() *generatedContributions {\n")
	buf.WriteString("\treturn &generatedContributions{}\n")
	buf.WriteString("}\n\n")

	// 4. clone method
	buf.WriteString("func (gc *generatedContributions) clone() *generatedContributions {\n")
	buf.WriteString("\tif gc == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tnext := newGeneratedContributions()\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\tnext.%s = cloneSlice(gc.%s)\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\tnext.%s = gc.%s\n", p.fieldName, p.fieldName)
		}
		if p.isExclusive {
			fmt.Fprintf(&buf, "\tnext.%sID = gc.%sID\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\tnext.%sHasID = gc.%sHasID\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\treturn next\n")
	buf.WriteString("}\n\n")

	// 5. freeze method
	buf.WriteString("func (gc *generatedContributions) freeze() *generatedFrozen {\n")
	buf.WriteString("\tif gc == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tgf := &generatedFrozen{\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t%s: cloneSlice(gc.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t%s: gc.%s,\n", p.fieldName, p.fieldName)
		}
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t\t%sID: gc.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t%sHasID: gc.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn gf\n")
	buf.WriteString("}\n\n")

	// 6. toContributions method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) toContributions() *generatedContributions {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn newGeneratedContributions()\n\t}\n")
	buf.WriteString("\tgc := newGeneratedContributions()\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\tgc.%s = cloneSlice(gf.%s)\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\tgc.%s = gf.%s\n", p.fieldName, p.fieldName)
		}
		if p.isExclusive {
			fmt.Fprintf(&buf, "\tgc.%sID = gf.%sID\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\tgc.%sHasID = gf.%sHasID\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\treturn gc\n")
	buf.WriteString("}\n\n")

	// 6b. freezeRequest method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) freezeRequest() *generatedFrozen {\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tnext := &generatedFrozen{\n")
	for _, p := range planes {
		if p.hasRequestMaterializer {
			if strings.HasPrefix(p.typeExpr, "[]") {
				fmt.Fprintf(&buf, "\t\t%s: materializeRequestSlice(gf.%s, %s.RequestMaterializer),\n", p.fieldName, p.fieldName, p.varName)
			} else {
				fmt.Fprintf(&buf, "\t\t%s: %s.RequestMaterializer(gf.%s),\n", p.fieldName, p.varName, p.fieldName)
			}
		} else if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t%s: cloneSlice(gf.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t%s: gf.%s,\n", p.fieldName, p.fieldName)
		}
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t\t%sID: gf.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t%sHasID: gf.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn next\n")
	buf.WriteString("}\n\n")

	// 7. contributeCandidateTo method on generatedFrozen
	buf.WriteString("func (gf *generatedFrozen) contributeCandidateTo(gc *generatedContributions, source SourceKind, contributorID string) error {\n")
	buf.WriteString("\tif gf == nil || gc == nil {\n\t\treturn nil\n\t}\n")
	for _, p := range planes {
		if !p.candidate {
			continue
		}
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\tif gf.%s != nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif %s.Validate != nil {\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\tif err := %s.Validate(gf.%s); err != nil {\n", p.varName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\treturn &AttributedError{\n\t\t\t\t\tPluginID: contributorID,\n\t\t\t\t\tPlaneID:  %s.ID,\n\t\t\t\t\tErr:      fmt.Errorf(\"%%w: %%w\", ErrInvalidContribution, err),\n\t\t\t\t}\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tif err := %s.generated.contribute(gc, source, contributorID, gf.%s); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", p.varName, p.fieldName)
		} else if p.typeExpr == "int" {
			fmt.Fprintf(&buf, "\tif gf.%s > 0 {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif %s.Validate != nil {\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\tif err := %s.Validate(gf.%s); err != nil {\n", p.varName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\treturn &AttributedError{\n\t\t\t\t\tPluginID: contributorID,\n\t\t\t\t\tPlaneID:  %s.ID,\n\t\t\t\t\tErr:      fmt.Errorf(\"%%w: %%w\", ErrInvalidContribution, err),\n\t\t\t\t}\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tif err := %s.generated.contribute(gc, source, contributorID, gf.%s); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", p.varName, p.fieldName)
		} else if p.isExclusive {
			fmt.Fprintf(&buf, "\tif gf.%s != nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif !gf.%sHasID || gf.%sID == \"\" {\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\treturn &AttributedError{\n\t\t\t\tPluginID: contributorID,\n\t\t\t\tPlaneID:  %s.ID,\n\t\t\t\tErr:      fmt.Errorf(\"%%w: frozen exclusive identity is missing\", ErrInvalidContribution),\n\t\t\t}\n", p.varName)
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tif gc.%sHasID {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\treturn makeExclusiveConflictError(contributorID, %s.ID, %s.ExclusiveConflictError, gc.%sID, gf.%sID)\n", p.varName, p.varName, p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tgc.%s = gf.%s\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\tgc.%sID = gf.%sID\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\tgc.%sHasID = true\n", p.fieldName)
			fmt.Fprintf(&buf, "\t}\n")
		} else {
			fmt.Fprintf(&buf, "\tif gf.%s != nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\tif %s.Validate != nil {\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\tif err := %s.Validate(gf.%s); err != nil {\n", p.varName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\treturn &AttributedError{\n\t\t\t\t\tPluginID: contributorID,\n\t\t\t\t\tPlaneID:  %s.ID,\n\t\t\t\t\tErr:      fmt.Errorf(\"%%w: %%w\", ErrInvalidContribution, err),\n\t\t\t\t}\n", p.varName)
			fmt.Fprintf(&buf, "\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t}\n")
			fmt.Fprintf(&buf, "\t\tif err := %s.generated.contribute(gc, source, contributorID, gf.%s); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n", p.varName, p.fieldName)
		}
	}
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	// 8. contributeCandidateMapTo function
	buf.WriteString("// contributeCandidateMapTo contributes map-backed candidate values into dst.\n")
	buf.WriteString("func contributeCandidateMapTo(values map[string]any, dst *ContributionSet, source SourceKind, contributorID string) error {\n")
	buf.WriteString("\tif len(values) == 0 || dst == nil {\n\t\treturn nil\n\t}\n")
	for _, p := range planes {
		if !p.candidate {
			continue
		}
		fmt.Fprintf(&buf, "\tif v, ok := values[%s.ID]; ok {\n", p.varName)
		buf.WriteString("\t\tif !isNilValue(v) {\n")
		fmt.Fprintf(&buf, "\t\t\ttyped, ok := v.(%s)\n", p.typeExpr)
		buf.WriteString("\t\t\tif !ok {\n")
		fmt.Fprintf(&buf, "\t\t\t\treturn &AttributedError{\n\t\t\t\t\tPluginID: contributorID,\n\t\t\t\t\tPlaneID:  %s.ID,\n\t\t\t\t\tErr:      fmt.Errorf(\"%%w: expected %s, got %%T\", ErrInvalidContribution, v),\n\t\t\t\t}\n", p.varName, p.typeExpr)
		buf.WriteString("\t\t\t}\n")
		fmt.Fprintf(&buf, "\t\t\tif err := ContributeSource(dst, %s, source, contributorID, typed); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n", p.varName)
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t}\n")
	}
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	// 9. init() binding closures
	buf.WriteString("func init() {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s.generated = generatedAccess[%s]{\n", p.varName, p.typeExpr)

		// contribute closure
		fmt.Fprintf(&buf, "\t\tcontribute: func(gc *generatedContributions, source SourceKind, pluginID string, v %s) error {\n", p.typeExpr)
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\tincoming := cloneSlice(v)\n")
			fmt.Fprintf(&buf, "\t\t\tcurrent := cloneSlice(gc.%s)\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.Combine(source, current, incoming)\n", p.varName)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tif (v != nil || gc.%s != nil) && combined == nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\tcombined = make(%s, 0)\n", p.typeExpr)
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = cloneSlice(combined)\n", p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.Combine(source, gc.%s, v)\n", p.varName, p.fieldName)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = combined\n", p.fieldName)
			if p.isExclusive {
				fmt.Fprintf(&buf, "\t\t\tid, hasID := %s.Identity(v)\n", p.varName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sID = id\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sHasID = hasID\n", p.fieldName)
			}
		}
		buf.WriteString("\t\t\treturn nil\n")
		buf.WriteString("\t\t},\n")

		// get closure
		fmt.Fprintf(&buf, "\t\tget: func(gf *generatedFrozen) %s {\n", p.typeExpr)
		buf.WriteString("\t\t\tif gf == nil {\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			buf.WriteString("\t\t\t\treturn nil\n")
		} else if p.typeExpr == "int" {
			buf.WriteString("\t\t\t\treturn 0\n")
		} else {
			buf.WriteString("\t\t\t\treturn nil\n")
		}
		buf.WriteString("\t\t\t}\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\treturn cloneSlice(gf.%s)\n", p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\treturn gf.%s\n", p.fieldName)
		}
		buf.WriteString("\t\t},\n")

		// identity closure
		if p.isExclusive {
			buf.WriteString("\t\tidentity: func(gf *generatedFrozen) (string, bool) {\n")
			buf.WriteString("\t\t\tif gf == nil {\n")
			buf.WriteString("\t\t\t\treturn \"\", false\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\treturn gf.%sID, gf.%sHasID\n", p.fieldName, p.fieldName)
			buf.WriteString("\t\t},\n")
		} else if p.hasIdentity {
			buf.WriteString("\t\tidentity: func(gf *generatedFrozen) (string, bool) {\n")
			buf.WriteString("\t\t\tif gf == nil {\n")
			buf.WriteString("\t\t\t\treturn \"\", false\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\treturn %s.Identity(gf.%s)\n", p.varName, p.fieldName)
			buf.WriteString("\t\t},\n")
		}

		buf.WriteString("\t}\n")
	}
	buf.WriteString("}\n\n")

	// 10. RequestExecutionView and methods
	buf.WriteString("// RequestExecutionView is an immutable borrowed view over request-materialized planes.\n")
	buf.WriteString("// Its returned slices must not be mutated.\n")
	buf.WriteString("type RequestExecutionView struct {\n")
	buf.WriteString("\tfrozen FrozenPlaneSet\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// RequestExecution constructs a RequestExecutionView over the request-materialized planes in in.\n")
	buf.WriteString("func RequestExecution(in FrozenPlaneSet) RequestExecutionView {\n")
	buf.WriteString("\treturn RequestExecutionView{frozen: in}\n")
	buf.WriteString("}\n\n")

	for _, p := range planes {
		if !p.requestBorrow {
			continue
		}
		pascalName := strings.TrimPrefix(p.varName, "Plane")
		fmt.Fprintf(&buf, "// %s returns the request-materialized %s without cloning.\n", pascalName, pascalName)
		buf.WriteString("// The returned slice is immutable borrowed storage and MUST NOT be mutated.\n")
		fmt.Fprintf(&buf, "func (v RequestExecutionView) %s() %s {\n", pascalName, p.typeExpr)
		buf.WriteString("\tif v.frozen.frozen == nil {\n\t\treturn nil\n\t}\n")
		fmt.Fprintf(&buf, "\treturn v.frozen.frozen.%s\n", p.fieldName)
		buf.WriteString("}\n\n")
	}

	// 11. Generation binder methods on *ContributionSet for replace-by-identity planes
	for _, p := range planes {
		if p.genBinderRule == "CombReplaceByIdentity" {
			pascalName := strings.TrimPrefix(p.varName, "Plane")
			fmt.Fprintf(&buf, "// Bind%s replaces %s under SourceGenerationBinder semantics.\n", pascalName, pascalName)
			fmt.Fprintf(&buf, "func (s *ContributionSet) Bind%s(contributorID string, v %s) error {\n", pascalName, p.typeExpr)
			fmt.Fprintf(&buf, "\treturn ContributeSource(s, %s, SourceGenerationBinder, contributorID, v)\n", p.varName)
			buf.WriteString("}\n\n")

			fmt.Fprintf(&buf, "// Replace%s replaces %s under SourceGenerationBinder semantics.\n", pascalName, pascalName)
			fmt.Fprintf(&buf, "func (s *ContributionSet) Replace%s(contributorID string, v %s) error {\n", pascalName, p.typeExpr)
			fmt.Fprintf(&buf, "\treturn ContributeSource(s, %s, SourceGenerationBinder, contributorID, v)\n", p.varName)
			buf.WriteString("}\n\n")
		}
	}

	// 12. ProjectDiagnostics function
	buf.WriteString("// ProjectDiagnostics projects diagnostic occupants and privileges from a frozen plane set.\n")
	buf.WriteString("func ProjectDiagnostics(in FrozenPlaneSet) []DiagnosticPlaneProjection {\n")
	buf.WriteString("\tif in.IsZero() {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tgf := in.frozen\n")
	buf.WriteString("\tif gf == nil && (in.values != nil || in.identities != nil) {\n")
	buf.WriteString("\t\tcset := in.ToContributions()\n")
	buf.WriteString("\t\tgf = cset.Freeze().frozen\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif gf == nil {\n\t\treturn nil\n\t}\n")
	buf.WriteString("\tvar projections []DiagnosticPlaneProjection\n\n")

	for _, p := range planes {
		if !p.hasDiagStageID {
			continue
		}
		fmt.Fprintf(&buf, "\t// Project %s\n", p.varName)
		buf.WriteString("\t{\n")
		fmt.Fprintf(&buf, "\t\tval := gf.%s\n", p.fieldName)
		fmt.Fprintf(&buf, "\t\tocc := %s.MaterializeOccupants(val)\n", p.varName)
		fmt.Fprintf(&buf, "\t\tpriv := %s.ProjectPrivileges(val)\n", p.varName)
		buf.WriteString("\t\tif len(occ) > 0 || len(priv.Flags) > 0 {\n")
		buf.WriteString("\t\t\tvar occCopy []DiagnosticOccupant\n")
		buf.WriteString("\t\t\tif len(occ) > 0 {\n")
		buf.WriteString("\t\t\t\toccCopy = make([]DiagnosticOccupant, len(occ))\n")
		buf.WriteString("\t\t\t\tfor i := 0; i < len(occ); i++ {\n")
		buf.WriteString("\t\t\t\t\to := occ[i]\n")
		buf.WriteString("\t\t\t\t\tvar pCopy []string\n")
		buf.WriteString("\t\t\t\t\tif len(o.Privileges) > 0 {\n")
		buf.WriteString("\t\t\t\t\t\tpCopy = append([]string(nil), o.Privileges...)\n")
		buf.WriteString("\t\t\t\t\t}\n")
		buf.WriteString("\t\t\t\t\toccCopy[i] = DiagnosticOccupant{\n")
		buf.WriteString("\t\t\t\t\t\tLabel:      o.Label,\n")
		buf.WriteString("\t\t\t\t\t\tPluginID:   o.PluginID,\n")
		buf.WriteString("\t\t\t\t\t\tPrivileges: pCopy,\n")
		buf.WriteString("\t\t\t\t\t}\n")
		buf.WriteString("\t\t\t\t}\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tvar privCopy []string\n")
		buf.WriteString("\t\t\tif len(priv.Flags) > 0 {\n")
		buf.WriteString("\t\t\t\tprivCopy = append([]string(nil), priv.Flags...)\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tprojections = append(projections, DiagnosticPlaneProjection{\n")
		fmt.Fprintf(&buf, "\t\t\t\tPlaneID:       %s.ID,\n", p.varName)
		fmt.Fprintf(&buf, "\t\t\t\tStageID:       %s.Diagnostics.StageID,\n", p.varName)
		fmt.Fprintf(&buf, "\t\t\t\tCoalesceGroup: %s.Diagnostics.CoalesceGroup,\n", p.varName)
		fmt.Fprintf(&buf, "\t\t\t\tOrder:         %s.Diagnostics.Order,\n", p.varName)
		buf.WriteString("\t\t\t\tOccupants:     occCopy,\n")
		buf.WriteString("\t\t\t\tPrivileges:    PrivilegeProjection{Flags: privCopy},\n")
		buf.WriteString("\t\t\t})\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t}\n\n")
	}

	buf.WriteString("\treturn projections\n")
	buf.WriteString("}\n\n")

	return buf.Bytes(), nil
}

func generateBundleProjectionCode(planes []planeInfo) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.\n\n")
	buf.WriteString("package featurebundle\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"errors\"\n\n")
	buf.WriteString("\tlipfeature \"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/feature\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// contributeFeatureBundleGenerated contributes all non-empty / non-nil planes from FeatureBundle b into cs.\n")
	buf.WriteString("func contributeFeatureBundleGenerated(cs *lipfeature.ContributionSet, pluginID string, b lipfeature.FeatureBundle) error {\n")
	buf.WriteString("\tif cs == nil {\n")
	buf.WriteString("\t\treturn errors.New(\"featurebundle: nil ContributionSet\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif pluginID == \"\" {\n")
	buf.WriteString("\t\tpluginID = \"feature\"\n")
	buf.WriteString("\t}\n")

	for _, p := range planes {
		pascalName := strings.TrimPrefix(p.varName, "Plane")
		switch {
		case isNilPresenceSlicePlane(p.planeID):
			fmt.Fprintf(&buf, "\tif b.%s != nil {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		case strings.HasPrefix(p.typeExpr, "[]"):
			fmt.Fprintf(&buf, "\tif len(b.%s) > 0 {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		case p.typeExpr == "int":
			fmt.Fprintf(&buf, "\tif b.%s > 0 {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		default: // exclusive / pointer / interface
			fmt.Fprintf(&buf, "\tif b.%s != nil {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		}
	}

	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func isNilPresenceSlicePlane(planeID string) bool {
	switch planeID {
	case "session_openers", "workspace_resolvers", "route_hint_providers", "completion_gates":
		return true
	default:
		return false
	}
}
