package archtest

import (
	"bytes"
	"fmt"
	"strings"
)

func generatePlanesCode(planes []planeInfo, sdkImports []string) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.\n\n")
	buf.WriteString("package feature\n\n")
	buf.WriteString("import (\n")
	for _, imp := range sdkImports {
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	// 1. generatedContributions struct
	buf.WriteString("// generatedContributions holds typed contribution storage for all declared feature planes.\n")
	buf.WriteString("type generatedContributions struct {\n")
	buf.WriteString("\tfreeze func() *generatedFrozen\n\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 2. generatedFrozen struct
	buf.WriteString("// generatedFrozen holds immutable typed snapshot storage for all declared feature planes.\n")
	buf.WriteString("type generatedFrozen struct {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s %s\n", p.fieldName, p.typeExpr)
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t%sID string\n", p.fieldName)
			fmt.Fprintf(&buf, "\t%sHasID bool\n", p.fieldName)
		}
	}
	buf.WriteString("}\n\n")

	// 3. newGeneratedContributions constructor
	buf.WriteString("// newGeneratedContributions constructs a new generatedContributions with an immutable snapshot freeze function.\n")
	buf.WriteString("func newGeneratedContributions() *generatedContributions {\n")
	buf.WriteString("\tgc := &generatedContributions{}\n")
	buf.WriteString("\tgc.freeze = func() *generatedFrozen {\n")
	buf.WriteString("\t\tgf := &generatedFrozen{\n")
	for _, p := range planes {
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\t%s: cloneSlice(gc.%s),\n", p.fieldName, p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\t%s: gc.%s,\n", p.fieldName, p.fieldName)
		}
		if p.isExclusive {
			fmt.Fprintf(&buf, "\t\t\t%sID: gc.%sID,\n", p.fieldName, p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t%sHasID: gc.%sHasID,\n", p.fieldName, p.fieldName)
		}
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\treturn gf\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn gc\n")
	buf.WriteString("}\n\n")

	// 4. init() binding closures
	buf.WriteString("func init() {\n")
	for _, p := range planes {
		fmt.Fprintf(&buf, "\t%s.generated = generatedAccess[%s]{\n", p.varName, p.typeExpr)

		// contribute closure
		fmt.Fprintf(&buf, "\t\tcontribute: func(gc *generatedContributions, source SourceKind, pluginID string, v %s) error {\n", p.typeExpr)
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\tincoming := cloneSlice(v)\n")
			fmt.Fprintf(&buf, "\t\t\tcurrent := cloneSlice(gc.%s)\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.Combine(source, current, incoming)\n", p.varName)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tif (v != nil || gc.%s != nil) && combined == nil {\n", p.fieldName)
			fmt.Fprintf(&buf, "\t\t\t\tcombined = make(%s, 0)\n", p.typeExpr)
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = cloneSlice(combined)\n", p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\tcombined, err := %s.Combine(source, gc.%s, v)\n", p.varName, p.fieldName)
			buf.WriteString("\t\t\tif err != nil {\n")
			buf.WriteString("\t\t\t\treturn err\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\tgc.%s = combined\n", p.fieldName)
			if p.isExclusive {
				fmt.Fprintf(&buf, "\t\t\tid, hasID := %s.Identity(v)\n", p.varName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sID = id\n", p.fieldName)
				fmt.Fprintf(&buf, "\t\t\tgc.%sHasID = hasID\n", p.fieldName)
			}
		}
		buf.WriteString("\t\t\treturn nil\n")
		buf.WriteString("\t\t},\n")

		// get closure
		fmt.Fprintf(&buf, "\t\tget: func(gf *generatedFrozen) %s {\n", p.typeExpr)
		buf.WriteString("\t\t\tif gf == nil {\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			buf.WriteString("\t\t\t\treturn nil\n")
		} else if p.typeExpr == "int" {
			buf.WriteString("\t\t\t\treturn 0\n")
		} else {
			buf.WriteString("\t\t\t\treturn nil\n")
		}
		buf.WriteString("\t\t\t}\n")
		if strings.HasPrefix(p.typeExpr, "[]") {
			fmt.Fprintf(&buf, "\t\t\treturn cloneSlice(gf.%s)\n", p.fieldName)
		} else {
			fmt.Fprintf(&buf, "\t\t\treturn gf.%s\n", p.fieldName)
		}
		buf.WriteString("\t\t},\n")

		// identity closure
		if p.isExclusive {
			buf.WriteString("\t\tidentity: func(gf *generatedFrozen) (string, bool) {\n")
			buf.WriteString("\t\t\tif gf == nil {\n")
			buf.WriteString("\t\t\t\treturn \"\", false\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\treturn gf.%sID, gf.%sHasID\n", p.fieldName, p.fieldName)
			buf.WriteString("\t\t},\n")
		} else if p.hasIdentity {
			buf.WriteString("\t\tidentity: func(gf *generatedFrozen) (string, bool) {\n")
			buf.WriteString("\t\t\tif gf == nil {\n")
			buf.WriteString("\t\t\t\treturn \"\", false\n")
			buf.WriteString("\t\t\t}\n")
			fmt.Fprintf(&buf, "\t\t\treturn %s.Identity(gf.%s)\n", p.varName, p.fieldName)
			buf.WriteString("\t\t},\n")
		}

		buf.WriteString("\t}\n")
	}
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}
