package archtest

import (
	"bytes"
	"fmt"
	"strings"
)

func generateBundleProjectionCode(planes []planeInfo) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scripts/generate-feature-planes.go. DO NOT EDIT.\n\n")
	buf.WriteString("package featurebundle\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"errors\"\n\n")
	buf.WriteString("\tlipfeature \"github.com/matdev83/go-llm-interactive-proxy/pkg/lipsdk/feature\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// contributeFeatureBundleGenerated contributes all non-empty / non-nil planes from FeatureBundle b into cs.\n")
	buf.WriteString("func contributeFeatureBundleGenerated(cs *lipfeature.ContributionSet, pluginID string, b lipfeature.FeatureBundle) error {\n")
	buf.WriteString("\tif cs == nil {\n")
	buf.WriteString("\t\treturn errors.New(\"featurebundle: nil ContributionSet\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif pluginID == \"\" {\n")
	buf.WriteString("\t\tpluginID = \"feature\"\n")
	buf.WriteString("\t}\n")

	for _, p := range planes {
		pascalName := strings.TrimPrefix(p.varName, "Plane")
		switch {
		case isNilPresenceSlicePlane(p.planeID):
			fmt.Fprintf(&buf, "\tif b.%s != nil {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		case strings.HasPrefix(p.typeExpr, "[]"):
			fmt.Fprintf(&buf, "\tif len(b.%s) > 0 {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		case p.typeExpr == "int":
			fmt.Fprintf(&buf, "\tif b.%s > 0 {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		default: // exclusive / pointer / interface
			fmt.Fprintf(&buf, "\tif b.%s != nil {\n", pascalName)
			fmt.Fprintf(&buf, "\t\tif err := lipfeature.Contribute(cs, lipfeature.%s, pluginID, b.%s); err != nil {\n", p.varName, pascalName)
			buf.WriteString("\t\t\treturn err\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString("\t}\n")
		}
	}

	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func isNilPresenceSlicePlane(planeID string) bool {
	switch planeID {
	case "session_openers", "workspace_resolvers", "route_hint_providers", "completion_gates":
		return true
	default:
		return false
	}
}
