// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: backendplugin/v1/backend.proto

package backendpluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendPlugin_Negotiate_FullMethodName        = "/golip.backendplugin.v1.BackendPlugin/Negotiate"
	BackendPlugin_Describe_FullMethodName         = "/golip.backendplugin.v1.BackendPlugin/Describe"
	BackendPlugin_Configure_FullMethodName        = "/golip.backendplugin.v1.BackendPlugin/Configure"
	BackendPlugin_CloseInstance_FullMethodName    = "/golip.backendplugin.v1.BackendPlugin/CloseInstance"
	BackendPlugin_ResolveProfile_FullMethodName   = "/golip.backendplugin.v1.BackendPlugin/ResolveProfile"
	BackendPlugin_ListModels_FullMethodName       = "/golip.backendplugin.v1.BackendPlugin/ListModels"
	BackendPlugin_CountTokens_FullMethodName      = "/golip.backendplugin.v1.BackendPlugin/CountTokens"
	BackendPlugin_FinalizeBilling_FullMethodName  = "/golip.backendplugin.v1.BackendPlugin/FinalizeBilling"
	BackendPlugin_Execute_FullMethodName          = "/golip.backendplugin.v1.BackendPlugin/Execute"
	BackendPlugin_Health_FullMethodName           = "/golip.backendplugin.v1.BackendPlugin/Health"
	BackendPlugin_GracefulShutdown_FullMethodName = "/golip.backendplugin.v1.BackendPlugin/GracefulShutdown"
)

// BackendPluginClient is the client API for BackendPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackendPlugin is the versioned local gRPC ABI for executable backend connectors.
// Transport-level automatic retries MUST be disabled by hosts and plugins.
type BackendPluginClient interface {
	Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*NegotiateResponse, error)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	CloseInstance(ctx context.Context, in *CloseInstanceRequest, opts ...grpc.CallOption) (*CloseInstanceResponse, error)
	ResolveProfile(ctx context.Context, in *ResolveProfileRequest, opts ...grpc.CallOption) (*ResolveProfileResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error)
	FinalizeBilling(ctx context.Context, in *FinalizeBillingRequest, opts ...grpc.CallOption) (*FinalizeBillingResponse, error)
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteClientFrame, ExecuteServerFrame], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GracefulShutdown(ctx context.Context, in *GracefulShutdownRequest, opts ...grpc.CallOption) (*GracefulShutdownResponse, error)
}

type backendPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendPluginClient(cc grpc.ClientConnInterface) BackendPluginClient {
	return &backendPluginClient{cc}
}

func (c *backendPluginClient) Negotiate(ctx context.Context, in *NegotiateRequest, opts ...grpc.CallOption) (*NegotiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Negotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) CloseInstance(ctx context.Context, in *CloseInstanceRequest, opts ...grpc.CallOption) (*CloseInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseInstanceResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_CloseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) ResolveProfile(ctx context.Context, in *ResolveProfileRequest, opts ...grpc.CallOption) (*ResolveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveProfileResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_ResolveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) FinalizeBilling(ctx context.Context, in *FinalizeBillingRequest, opts ...grpc.CallOption) (*FinalizeBillingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeBillingResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_FinalizeBilling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteClientFrame, ExecuteServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendPlugin_ServiceDesc.Streams[0], BackendPlugin_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteClientFrame, ExecuteServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_ExecuteClient = grpc.BidiStreamingClient[ExecuteClientFrame, ExecuteServerFrame]

func (c *backendPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) GracefulShutdown(ctx context.Context, in *GracefulShutdownRequest, opts ...grpc.CallOption) (*GracefulShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GracefulShutdownResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_GracefulShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendPluginServer is the server API for BackendPlugin service.
// All implementations must embed UnimplementedBackendPluginServer
// for forward compatibility.
//
// BackendPlugin is the versioned local gRPC ABI for executable backend connectors.
// Transport-level automatic retries MUST be disabled by hosts and plugins.
type BackendPluginServer interface {
	Negotiate(context.Context, *NegotiateRequest) (*NegotiateResponse, error)
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	CloseInstance(context.Context, *CloseInstanceRequest) (*CloseInstanceResponse, error)
	ResolveProfile(context.Context, *ResolveProfileRequest) (*ResolveProfileResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error)
	FinalizeBilling(context.Context, *FinalizeBillingRequest) (*FinalizeBillingResponse, error)
	Execute(grpc.BidiStreamingServer[ExecuteClientFrame, ExecuteServerFrame]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	GracefulShutdown(context.Context, *GracefulShutdownRequest) (*GracefulShutdownResponse, error)
	mustEmbedUnimplementedBackendPluginServer()
}

// UnimplementedBackendPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendPluginServer struct{}

func (UnimplementedBackendPluginServer) Negotiate(context.Context, *NegotiateRequest) (*NegotiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedBackendPluginServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedBackendPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedBackendPluginServer) CloseInstance(context.Context, *CloseInstanceRequest) (*CloseInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseInstance not implemented")
}
func (UnimplementedBackendPluginServer) ResolveProfile(context.Context, *ResolveProfileRequest) (*ResolveProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveProfile not implemented")
}
func (UnimplementedBackendPluginServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedBackendPluginServer) CountTokens(context.Context, *CountTokensRequest) (*CountTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedBackendPluginServer) FinalizeBilling(context.Context, *FinalizeBillingRequest) (*FinalizeBillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeBilling not implemented")
}
func (UnimplementedBackendPluginServer) Execute(grpc.BidiStreamingServer[ExecuteClientFrame, ExecuteServerFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedBackendPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBackendPluginServer) GracefulShutdown(context.Context, *GracefulShutdownRequest) (*GracefulShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GracefulShutdown not implemented")
}
func (UnimplementedBackendPluginServer) mustEmbedUnimplementedBackendPluginServer() {}
func (UnimplementedBackendPluginServer) testEmbeddedByValue()                       {}

// UnsafeBackendPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendPluginServer will
// result in compilation errors.
type UnsafeBackendPluginServer interface {
	mustEmbedUnimplementedBackendPluginServer()
}

func RegisterBackendPluginServer(s grpc.ServiceRegistrar, srv BackendPluginServer) {
	// If the following call pancis, it indicates UnimplementedBackendPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendPlugin_ServiceDesc, srv)
}

func _BackendPlugin_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Negotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Negotiate(ctx, req.(*NegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_CloseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).CloseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_CloseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).CloseInstance(ctx, req.(*CloseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_ResolveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).ResolveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_ResolveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).ResolveProfile(ctx, req.(*ResolveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).CountTokens(ctx, req.(*CountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_FinalizeBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeBillingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).FinalizeBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_FinalizeBilling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).FinalizeBilling(ctx, req.(*FinalizeBillingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendPluginServer).Execute(&grpc.GenericServerStream[ExecuteClientFrame, ExecuteServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_ExecuteServer = grpc.BidiStreamingServer[ExecuteClientFrame, ExecuteServerFrame]

func _BackendPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_GracefulShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GracefulShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).GracefulShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_GracefulShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).GracefulShutdown(ctx, req.(*GracefulShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendPlugin_ServiceDesc is the grpc.ServiceDesc for BackendPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golip.backendplugin.v1.BackendPlugin",
	HandlerType: (*BackendPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Negotiate",
			Handler:    _BackendPlugin_Negotiate_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _BackendPlugin_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _BackendPlugin_Configure_Handler,
		},
		{
			MethodName: "CloseInstance",
			Handler:    _BackendPlugin_CloseInstance_Handler,
		},
		{
			MethodName: "ResolveProfile",
			Handler:    _BackendPlugin_ResolveProfile_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _BackendPlugin_ListModels_Handler,
		},
		{
			MethodName: "CountTokens",
			Handler:    _BackendPlugin_CountTokens_Handler,
		},
		{
			MethodName: "FinalizeBilling",
			Handler:    _BackendPlugin_FinalizeBilling_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BackendPlugin_Health_Handler,
		},
		{
			MethodName: "GracefulShutdown",
			Handler:    _BackendPlugin_GracefulShutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _BackendPlugin_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "backendplugin/v1/backend.proto",
}
