# Hygiene + heavy regression matrices (//go:build precommit). Not part of default go test ./...
$ErrorActionPreference = "Stop"
go test -parallel=8 -tags=precommit ./internal/qa/... ./internal/core/runtime/...
exit $LASTEXITCODE
