#!/usr/bin/env bash
# Hygiene + heavy regression matrices (//go:build precommit). Not part of default go test ./...
set -euo pipefail
go test -short -parallel=8 -tags=precommit ./internal/qa/... ./internal/core/runtime/...
